### ISSUE TITLE
Can you add a replacer? This replacer can replace-NOERROR-but-zero-answer to SERVFAIL.

### ISSUE THREAD

**Issue by iamsurfing** [folbricht/routedns#102]
```
; <<>> DiG 9.17.5 <<>> dropbox.com MX
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46028
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; CLIENT-SUBNET: 0.0.0.0/32/0
;; QUESTION SECTION:
;dropbox.com.                   IN      MX

;; Query time: 59 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN:  ;; MSG SIZE  rcvd: 52
```
Some public DNS will return a bad response like this following. (It is hard to answer which DNS.)Therefore, can you add a replacer? This replacer can replace NOERROR-but-zero-answer to SERVFAIL.
(Test passed. Is there anybody who can pull request? I do not know how to use git.)

> badResponseFilter.go

```
package rdns

import (
	"github.com/miekg/dns"
)

type badResponseFilter struct {
	id       string
	resolver Resolver
}

var _ Resolver = &badResponseFilter{}

func NewbadResponseFilter(id string, resolver Resolver) *badResponseFilter {
	return &badResponseFilter{id: id, resolver: resolver}
}

func (r *badResponseFilter) Resolve(q *dns.Msg, ci ClientInfo) (*dns.Msg, error) {
	a,err:=r.resolver.Resolve(q, ci)
	//debug
	//replace NOERROR-but-zero-answer to SERVFAIL
	if err==nil&&a!=nil{
		if (len(a.Answer)==0&&a.Rcode==dns.RcodeSuccess){
			n:=new(dns.Msg)
			n.SetRcode(a,dns.RcodeServerFailure)
			return n,err
		}
	}
	//If you have bad response to be filtered, you can add your code there.
	//debug
	return a, nil
}

func (r *badResponseFilter) String() string {
	return r.id
}
```

> Add it to main.go, line 266

```
//switch g.Type {
	case "bad-response-filter":
		if len(gr) != 1 {
			return fmt.Errorf("type bad-response-filter only supports one resolver in '%s'", id)
		}
		resolvers[id] = rdns.NewbadResponseFilter(id, gr[0])
//}
```

> configuration

```
[groups.group1]
  resolvers=["resolver"]
  type="bad-response-filter"
```

**Comment by cbuijs** [comment]
Maybe a rule in `routers` with as argument the returncode? See #96. 
```
[routers.fixservfail]
routes [
  { rcode = "SERVFAIL", resolver = "noerror" },
  { resolver = "default" },
]

[groups.noerror]
type  = "static-responder"
rcode = 0
```

**Comment by cbuijs** [comment]
Sorry, did read that wrongly and provided nonsense (keeping the example for #96 though).

I think it is better to return "NXDOMAIN" when a "NOERROR" with no answers is given, you can already enforce this using the <a href="https://github.com/folbricht/routedns/blob/master/doc/configuration.md#Response-Collapse">Response-Collapse</a> group type.

**Comment by iamsurfing** [comment]
@cbuijs 

First, in my opinion, router is just filter for request not response.

Second one. Yes, I read it. But you did not say block it by count of answer.

**Comment by iamsurfing** [comment]
So, is there anyone who can help me pull request?

**Comment by folbricht** [comment]
If we had a response-router component already, this would be easy to do with a static responder. Sounds like something for the v2 wishlist.

Now, this could be implemented quite easily with a dedicated component (got a good name for it)? Also, what's zero answer in this case? One that has no element in the "Answer" section, or should the question and additional records be considered at all as well?

**Comment by iamsurfing** [comment]
It is not inportant problem for me. However, if apply it, it will inprove some bad public DNS experience.

Public DNS must return SERVFAIL if get incorrent response. But, a lot of DNS is not standard, it will return NOERROR if get response. However, could not find record in cache, because it can not find current record. Finally, it will return NOERROR-but-zero-answer response to client.

File name is not good, so I renamed it to bad-filter. It is easy to understand. If others have bad response to be filtered, they can add their code.

I think this check&replace shound be embeded to resolvers.go. But it is bad to add or modify code file of resolver .

**Comment by iamsurfing** [comment]
I will keep using routedns with this modify. If stable, I will pull request.
