### ISSUE TITLE
Define resolver when response-collapse has zero answers left

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#108]
Would it be possible to have a configurable resolver for the `response-collapse` group when after collapsing no answers are left? It defaults to `NXDOMAIN` today.

Basically like the `response-blocklist-ip` group.

Use case here that NXDOMAIN generates additional lookups in the possible search-domains defined by the DNS clients. Providing (as example) a `NOERROR` with no answers stops this and keeps the noise down, or jump to another/alternate resolver that might have an answer (switch from external to internal resolution as example).

**Comment by folbricht** [comment]
I'm thinking of adding an `rcode=3` option to it that would define the response in that case. Problem is that it would slightly change the default behavior and return OK when there's nothing left after collapsing. Though arguably that's the better default anyway, isn't it?

**Comment by folbricht** [comment]
There's now a draft implementation on the `issue-108` branch. It changes the default behavior of `response-collapse` to return OK, and adds a new option `null-rcode = 3` to it, similar to the rcode option on the static responder. Let me know if this works the way you'd expect. I didn't fully test it, didn't have an easy example that would collapse down to nothing.

**Comment by cbuijs** [comment]
I'll will test this. But for testing purposes you can use this:

`dig @127.0.0.1 www.paypal.com AAAA`

It is a cname-chain without an IP-Address and collapses into an empty answer.

**Comment by cbuijs** [comment]
Works great!
