### ISSUE TITLE
Can you add Sequance-Request in Groups?

### ISSUE THREAD

**Issue by iamsurfing** [folbricht/routedns#110]
For example. I have 2 public DNS servers. DNS1 can return the nearest IP but network failure usually happen. DNS2 can not return the nearest IP but stable.

Therefore, I want DNS1 as the main DNS. DNS2 work only if DNS1 could not work.

(It should support equal or more than 1 resolver.)

(Do not forget to solve SERVFAIL.)#99

Q:Why not Round-Robin, Fail-Rotate and Fail-Back?

A:Because it will save state. If it switches to DNS2, it will affect my surfing-the-Internet experience.

**Comment by folbricht** [comment]
So how about a "fastest" group? An incoming query is sent to all resolvers, and the first response is returned while the others are dropped. Would that solve it? Or are you looking for something that always tries resolver1 first, then if that fails for any reason tries resolver2. This would be a bit slower overall, but wouldn't make the extra/unnecessary queries.

**Comment by iamsurfing** [comment]
Agree. I prefer "fastest" group, because it is useful.

**Comment by folbricht** [comment]
An implementation of this exists on the `issue-110` branch now if you'd like to give it a try.

It's quite simple to use
```toml
[groups.fastest]
type   = "fastest"
resolvers = ["cloudflare-dot-1", "cloudflare-dot-2", "google-dot"]
```

**Comment by iamsurfing** [comment]
It is FASTEST. Thank you.

**Comment by cbuijs** [comment]
How does this work when only using one-resolver that has multiple IP-Addresses? Like `https://dns.google/dns-query` has 4 IP-Addresses (resolving `dns.google`). How do you consider the "fastest", I think this should be done on `resolver` level and not on `group`? Or perhaps both, or specify bootstrap-addresses for every resolver? Seems a bit clunky?

**Comment by folbricht** [comment]
If a resolver is configured with a hostname and has multiple IPs, it'll just use any one of them, like it does at the moment.  There isn't an easy way to do it on the resolver itself and distinguish between its IPs, it'd go extremely deep into the connection handling and failover. To get control over multiple IPs behind one name, it's best to define them as individual resolvers using their IPs directly and then putting a "fastest" in front. In most cases that's best anyway to avoid the initial lookup for the resolver IPs slowing everything down.

**Comment by iamsurfing** [comment]
@cbuijs 

Why google have double DNS? Because middle-box may drop UDP packet. Double DNS can make resolve faster.

It is useless in TCP.

**Comment by cbuijs** [comment]
@folbricht Gotcha, kind of figured that out. Maybe an idea to have a similar version of this feature in the future, more based on RTT and synthetic degradation like BIND does (Called SRTT)?

@iamsurfing Actually all IP's are ANYCASTED anyway, making queries to all DNS-Servers at once and pick the quickest return is quit taxing (traffic gets duplicated, DNSMasq has this feature as well), and not efficient, it is a trade-off of bandwidth vs availability vs performance. The protocol it self (either UDP and DNS) has enough mechanism build-in to be fail-safe, doing multi-query just makes it marginally faster and then cache takes over anyway, it generates more traffic as trade-off, so the effect is little in my opinion (still a cool feature though!).

**Comment by folbricht** [comment]
Merged in https://github.com/folbricht/routedns/pull/112, there's a warning in the docs about this multiplying the query load. This should be used with care
