### ISSUE TITLE
ROUTERS: Return/Enforce answer immediately as feature of a rule

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#113]
Would it be possible to have something like this as a `routers` rule:

`{invert = true, class = "IN", resolver = "nxdomain", enforce = true},`

Where the `enforce = true` is the new bit.

So Instead of traversing back up/to other groups/etc that can (also) mangle or process the answer, just shortcut and give/enforce the answer as given by the rule and respond immediately to the client (cutting off any additional processing that might occur)? This so that you are sure THAT will be THE answer, and not something generated or get replaced-by  back up the chain?

Potentially this would cut some unnecessary complexity in some cases and processing as a whole?

**Comment by folbricht** [comment]
That's not easily doable. RouteDNS uses a call stack, so responses need to go back the same way the query came in from. It doesn't route queries and responses freely between components (would have to design it differently). Could try to "freeze" the response, telling the callers to not modify it in any way, but that would be quite ugly.

Do you have a use-case for it? Perhaps that could be achieved differently.

**Comment by cbuijs** [comment]
Use case is that I have the collapser and minimizer before filtering/routing, and I use multiple resolvers, when I return a RCODE like REFUSED or NXDOMAIN, it get over-rulled by the collapser. I can move the collapser/minimizer closer to the resolvers but then need it "per" resolver. Which is do-able but klunky, and also disable CNAME response filtering (as it is collapsed).

**Comment by folbricht** [comment]
Hmm, sounds more like a bug in the collapser, it probably shouldn't do anything unless the code is OK. That'd be a simple change.

**Comment by folbricht** [comment]
I fixed the minimizer and collapser on the `issue-113` branch if you want to try those out. They'll no longer touch anything that's not successful and pass NXDOMAIN or SERVFAIL right through.

**Comment by cbuijs** [comment]
Perfect! Thanks! Works as expected!

**Comment by folbricht** [comment]
Thanks, merged in https://github.com/folbricht/routedns/pull/114
