### ISSUE TITLE
Return ID-0 record when QUIC request timeout.

### ISSUE THREAD

**Issue by iamsurfing** [folbricht/routedns#119]
resolver
`dns-unfiltered.adguard.com:784`
routedns log
`time="" level=error msg="failed to resolve" addr=":53" client=127.0.0.1 error="deadline exceeded" id=udp protocol=udp qname=`
warning in dig tool
`;; Warning: ID mismatch: expected ID 61376, got 0`
`;; Warning: ID mismatch: expected ID 61376, got 0`

I hope dig-tool will not return this warning.

**Comment by folbricht** [comment]
Thanks for reporting that. The issue was that in DoQ, the ID has to be set to 0 when sending the query. I didn't undo that in the error-case though which is what caused this. Fixed in https://github.com/folbricht/routedns/pull/120
