### ISSUE TITLE
Latest build (e962ab8) gives "edge between" errors

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#121]
With/Since the latest <a href="https://github.com/folbricht/routedns/commit/e962ab8023eb8f5ab56ce3736e02d79edad362ee">build (e962ab8)</a>, I am getting the following error (no config changes since previous builds):

`Error: edge between 'router' and 'drop' is already known`

The piece of config it trips over:
```
[routers.router]
routes = [
        {invert = true, class = "IN", resolver = "drop"},
        {invert = true, types = ["A", "AAAA", "CAA", "CNAME", "HTTPS", "MX", "NAPTR", "PTR", "SRV", "SVCB", "TXT"], resolver = "drop"},

        {name = '^\.$', resolver = "drop"},
        {name = '(^|\.)(arpa|bind|global|home|lan|loca(l|lhost|lnet)(4|6)*|router|workgroup)\.$', resolver = "drop"},

        {source = "127.0.0.1/32", resolver = "doh-resolver"},
        {source = "::1/128", resolver = "doh-resolver"},

        {resolver = "tld"},
]
```

**Comment by folbricht** [comment]
Ah, right, I know why that's happening. Will try to fix shortly

**Comment by folbricht** [comment]
Should be fixed in  https://github.com/folbricht/routedns/pull/122
