### ISSUE TITLE
Change logging time-stamp

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#125]
Looks like the logging produced by RouteDNS defaults to "Zulu" (UTC) time by default. It would be great if the time-zone is configurable for logging.

`time="2021-01-12T08:34:45Z" level=debug msg="reloading blocklist" id=home-hosts`

**Comment by folbricht** [comment]
Can you check what the machine's timezone is set to? I just double-check one mine, it's using whatever the machine uses for me. It should already be respecting the OS' timezone.

**Comment by cbuijs** [comment]
```
root@OpenWrt:~# date +%Z
CET
```

**Comment by folbricht** [comment]
What version of Go are you using? I wonder if you're running into https://github.com/golang/go/issues/42138. Might be worth grabbing the latest just in case

**Comment by cbuijs** [comment]
Version 1.15.6 of GO.

I found the culprit, it is an openwrt system which standard has no zoneinfo or/and `/etc/localtime`. Creating it fixed the problem

Fix (for openwrt in this case):
```
opkg update && opkg install zoneinfo-europe
ln -s /usr/share/zoneinfo/CET /etc/localtime
```
