### ISSUE TITLE
Add round-robin feature to cache

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#126]
When an answer is cached, the order of the records stay the same every time an answer is provided to a DNS client from cache.

It would be nice to have a feature on cache to round-robin the answers on every hit. This would be relevant only to the answer section and only to address-records when more then one.

A "random" option would be a nice-to-have as well.

The case here is to provide a synthetic "balancing" option and distribute connections more evenly instead just to the first address in a record-set as example, the first one now becomes "sticky" and in some cases this is unwanted and this would solve it.

Default should be NOT to mess with the order (as it is now), as there are many GSLB solutions steering DNS answers and relying on the order.

**Comment by folbricht** [comment]
Good idea. It could be integrated into the cache, but to offer more flexibility, how about making some sort of `response-shuffle` component that could be used in front of the cache, or in other places. Randomizing the response is far easier, since round-robin would mean there's state to be maintained internally for every response.

**Comment by cbuijs** [comment]
I was thinking cache as you update the cache entry with the new order (but keep ttl going). So no state needed.

**Comment by folbricht** [comment]
There's a first implementation on the `issue-126` branch. The cache now has a new option `cache-answer-shuffle` with values `random` and `round-robin`. If the option is not provided, it'll keep returning static responses. Should look like this:

```toml
[groups.cloudflare-cached]
type = "cache"
resolvers = ["cloudflare-dot"]
cache-answer-shuffle = "round-robin
```
Let me know if that solves the issue.

Oh, and it blindly rotates all answers, regardless of type (not just A and AAAA). I don't think that matters, does it?

**Comment by cbuijs** [comment]
I think it is important only touch `A` and `AAAA` records in a RRSet. Some clients lack "intelligence" and just follow the rrset records in order. For example, when you resolve `www.paypal.com`, it results in a bunch of CNAME's first, and the address-records are at the end of the RRSet. They kind of all rely/depend on each other in order with exception of the address records. This might be solved by `collapsing` the answers first before it reaches the cache.

I will try to do some tests this weekend to see if it breaks stuff.

**Comment by folbricht** [comment]
I should be able to make it work that way. What should happen if for example the A records are not next to each other like so
1. A
2. CNAME
3. AAAA
4. A

Should only poisitions 1, 3, 4 be shifted? Or should the shuffle only happen on one kind of addresses (shuffle A and AAAA in their existing positions independently)?

**Comment by cbuijs** [comment]
So normally that shouldn't happen, you keep the address-record at the end. But if it does (lots of crappy DNS software out there), only the positions that have address-records shift indeed (I would re-order first and move them to the end myself).

Also, never seen a combination of A and AAAA together in the same RRSet as you can not query both at the same time :-). You can request the CNAME, but then the answer will only have that, not the Address-records. Other way around is possible, asking for an A or AAAA and get a CNAME chain RRSET back.

**Comment by cbuijs** [comment]
Tested` issue-126` branch, and seems to have the effect looking for without any direct adverse side-effects with my apps, services, etc in the short period I checked.

I did notice more lookups for the search and local domains then usual when switched on (round-robin), and goes down when switched off (no round-robin), but didn't seem to hurt anything. Maybe when testing/using for a longer period when all caches of servers/clients bleed empty or something, something will pop up. It just feels a bit not-good.

**Comment by folbricht** [comment]
Thanks for testing it. I'll still come up with a shuffle for just the address records while leaving the others alone. Might take a bit though.

**Comment by cbuijs** [comment]
Running the whole day already together with the `response-collapse` which only leaves the rrset as address-records only anyway, and no weird things or side-effects so far. For me this is fine. But might not fit other cases where collapsing is not used (see my previous test).

**Comment by cbuijs** [comment]
Actually....

Run below commands several times:

`dig @1.1.1.1 google.com TXT`

and

`dig @1.1.1.1 hp.com A`

And then against your RouteDNS with round-robin active, and the results are actually the same, so looks we are good to go!

Above command (first one) resolve non-address records, and they are rotating too.

**Comment by folbricht** [comment]
Finally had time to update the shuffle algorithm on the `issue-126` branch to only rotate/shuffle the A or AAAA records in an answer. I'll leave everything else in the same position. This should be safer. Let me know if that looks ok.

**Comment by cbuijs** [comment]
Just did some quick tests with this update, works as expected and no surprises or extra traffic as seen before. So thumbs up from me!

**Comment by folbricht** [comment]
Merged in https://github.com/folbricht/routedns/pull/128, thanks
