### ISSUE TITLE
Harden Cache on subdomains of parent NXDOMAIN

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#131]
See also `harden-below-nxdomain` feature of [unbound](https://nlnetlabs.nl/documentation/unbound/unbound.conf/).

Basically, if a query comes in, and the parent-domain of the query is already in cache with a `NXDOMAIN`, return `NXDOMAIN` for that query too.

Basically, if `parent.domain.com` already sits in cache as a `NXDOMAIN` answer, then when `www.parent.domain.com` is queried, it gets a `NXDOMAIN` as answer too.

To do it save, you might want to make sure the parent `NXDOMAIN` is "secure" e.g. validated by using DNSSEC (as stated in unbound documentation). But from my personal opinion/observation, this could be optional (or a "later" feature).

**Comment by folbricht** [comment]
That looks like the `harden-below-nxdomain` option in unbound. Definitely doable, I'll leave it off by default for now though since there's no DNSSEC validation yet.
I really need to get back to implementing DNSSEC.

**Comment by folbricht** [comment]
There's a first implementation on the `issue-131` branch if you want to try it out. The logs should just say "cache hit" and won't actually say it's due to the new flag.

```toml
cache-harden-below-nxdomain = true
```

**Comment by cbuijs** [comment]
Seems to be working as designed. Running it for two days straight without any issues so far.
