### ISSUE TITLE
Weird cache/answer behaviour using "replace" (section mismatch)

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#134]
When using this:

```
[groups.add-home]
type = "replace"
resolvers = ["cache"]
replace = [
  {from = '^([^\.]+)\.$', to = '${1}.home.'},
]
```
And I resolve this:

`dig nohome`

All goes according plan/expectations (.home is added, and that is resolved fine). But then after when I resolve this:

`dig nohome.home`

I get an error stating this:

`;; Question section mismatch: got nohome/A/IN`

Still get the right answer though.

I think some logic on how things are stored in `cache` when a replace is used, is off. Doesn't matter if i put `cache` before or after in the chain.

The other way around (doing `.home` first and then without) is working fine with no errors.

**Comment by folbricht** [comment]
Great find, thank you. Fixed in https://github.com/folbricht/routedns/pull/135

**Comment by cbuijs** [comment]
The behaviour changed, but now getting a different error (same setup/execution) with `master` / [22732b2](https://github.com/folbricht/routedns/commit/22732b2451619fe6afd0e23a50cae4ea783be262) :

`;; Question section mismatch: got nohome/A/IN`

Impact is minimal, seems that applications and such don't care (horrifying security hole), or just give a "cannot resolve" answer, just pops up when you use `dig` and such.

Seems that the question-section of the answer needs to be the same with the question-section of the query. Perhaps index the cache with the query-question-section?

**Comment by cbuijs** [comment]
Fixed it. Above only happens when the `replace` sits **after** `cache`. If it sits **before** all is dandy.

**Comment by folbricht** [comment]
Interesting, could be the same issue, but in a different place. Will take a look.

**Comment by folbricht** [comment]
Could you try the `issue-134-2` branch? That should fix it, but I haven't had time to fully test it.

**Comment by cbuijs** [comment]
Problem stays with `issue-134-2`, no change at all actually. Before cache works, after gives:

`;; Question section mismatch: got nohome/A/IN`

**Comment by folbricht** [comment]
Ah, was able to repro it, similar issue but in another spot. Should be fixed on the branch now. Thanks again for bringing that up.

**Comment by cbuijs** [comment]
I'll give it a go later today, thanks for the quick turnaround!

**Comment by cbuijs** [comment]
Works! No more errors, using `replace` before or after `cache`.

**Comment by folbricht** [comment]
Merged in https://github.com/folbricht/routedns/pull/136, thank you for checking it out, and for reporting the issue
