### ISSUE TITLE
Upgrade to quic-go v0.20.0

### ISSUE THREAD

**Issue by galpt** [folbricht/routedns#138]
Got this error when trying to upgrade from **quic-go v0.19.3** to **v0.20.0**

```
# github.com/folbricht/routedns
..\..\dohclient.go:301:9: cannot use &quicSession{...} (type *quicSession) as type quic.EarlySession in return argument:
        *quicSession does not implement quic.EarlySession (missing NextSession method)
```

**Comment by cbuijs** [comment]
Same here, 0.19.3 compiles/works just fine.

**Comment by folbricht** [comment]
Looks like the signature changed, I'll take a look and update to match the new one.

**Comment by folbricht** [comment]
There's an update on the issue-138 branch now (https://github.com/folbricht/routedns/pull/146) that updates all deps.

**Comment by galpt** [comment]
Thanks! Looks good and compiles fine.
I'm closing this issue now.
