### ISSUE TITLE
Cache has no default value for cache-answer-shuffle and breaks when not defined 

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#139]
Little bug, when no `cache-answer-shuffle` is provided on cache, routedns stops with the error message:

`Error: unsupported shuffle function ""`

Perhaps the value "static" should be allowed and selected as default?

P.S. Also seems to be some spelling-mistakes in the func-names (rando**n** instead of rando**m**).

**Comment by folbricht** [comment]
Oops, how embarrassing. Missed it. Fixed in https://github.com/folbricht/routedns/pull/141

**Comment by cbuijs** [comment]
Fixed!
