### ISSUE TITLE
Make dialer timeout configurable

### ISSUE THREAD

**Issue by mikhirev** [folbricht/routedns#140]
Hi!

I've got in trouble when one of upstream resolvers became unavailable. It should failed back to another one, but instead of this it was waiting for TCP connection (it happens both with DoT and plain TCP connections) for a very long time. I'd like to have possibility to configure `net.Dialer.Timeout` to mitigate this.

As I use `rdns` as a module in my project, it would be enough for me if `DNSClient.pipeline`, `DoTClient.pipeline` and `Pipeline.client` were exported. But I suppose that adding a configuration option to routedns itself can also be useful for its users.

**Comment by folbricht** [comment]
Yes, that should be configurable, it's likely not an issue for DoH as that uses contexts. I started working on the `issue-140` branch but don't have time to test or complete the implementation just yet. It should in theory work for DNS and DoT though if you want to give it a try.

**Comment by mikhirev** [comment]
Hmm, it's strange, but I can't reproduce the hang artificially. It works like there's 1 second timeout set, both with my old builds and with code from `issue-140`, and I couldn't figure out where it comes from. I need more time for investigation…

**Comment by mikhirev** [comment]
I'm sorry, I mislead you. There's some problem with both failback and failrotate resolvers that occurs under heavy load when one of upstream resolvers is unreachable, but it is not related to TCP timeouts. This issue is irrelevant.
