### ISSUE TITLE
Requests stuck when dialing a resolver takes too long

### ISSUE THREAD

**Issue by mikhirev** [folbricht/routedns#143]
Finally I figured out the cause of my problem previously described in #140. It happens under heavy load when packets to one of upstream resolvers are dropped somewhere. It happens here:

https://github.com/folbricht/routedns/blob/2a699efccb74ff552f4016418f396d1055b2288a/pipeline.go#L48-L51

Queuing a request waits for all previous ones. If many requests are to be queued, their timeouts sum up.

**Comment by folbricht** [comment]
Thanks for the fix. While this is a good change, the lack of dial timeout for DoT is still an issue. With your fix it won't have a noticeable impact though. I'll come back to it at some point.
