### ISSUE TITLE
Outdated alpn value for the DNS over quic support.

### ISSUE THREAD

**Issue by VanStratum** [folbricht/routedns#147]
The alpn value for opening a doq connection was changed from "dq" to "doq" in draft-ietf-dprive-dnsoquic-00. 
As far as I can tell, the only things to change is the following line from doqclient and doqlistener:
`opt.TLSConfig.NextProtos = []string{"dq"}`

**Comment by folbricht** [comment]
Thanks for letting me know. I must have missed that.
