### ISSUE TITLE
Select "Fastest Server" feature

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#149]
Tested some stuff with [Adguard DNSProxy](https://github.com/AdguardTeam/dnsproxy) and the `--fastest-addr` feature.

It actually works very well, and was wondering how much effort it is to build something similar for RouteDNS.

In short:
- The IP's of A or AAAA records coming in a response are tested with a Connect test and RTT of that is measured.
- Only the IP-Address with "fastest" RTT is returned to the DNS Client (and cached).

Some nice benefits: Connections seems to be more "snappy" on some sites and DNS responses are reduced in size (smaller packets on the network, less bandwidth).

A "con" is maybe that the first query, before caching takes potentially longer (because of the tests), but I didn't notice this from a "user" perspective. Also more "connects" flow out of my gateway due to the tests, but is negligible due to caching again.

Could be part of `response-collapse` maybe (make an option `fastest = true` or something)?

See also:
[Fastest addr + cache-min-ttl](https://github.com/AdguardTeam/dnsproxy#fastest-addr--cache-min-ttl).
[fastest_addr.go](https://github.com/AdguardTeam/dnsproxy/blob/63ee0fbc04e85f7b8492657c344950935fee1b30/fastip/fastest_addr.go)

**Comment by folbricht** [comment]
Interesting, but I see quite a few issues with that, surprised it works properly for you. It would have to be slower on the first attempt, though that could be improved with caching of course. But more importantly, it makes assumptions about what sort of server and protocol it is, though it can't possibly know that. So for example it always assumes that it's TCP, and that the port is 80 or 443. Under load it'd also open quite a lot of connections and have goroutines building up.

Is that really working and making a difference when browsing the web? I wonder if there's a better way to choose fastest (closest), perhaps by using the GeoIP DB?

**Comment by cbuijs** [comment]
Surprisingly it works quite well. Number of connections open on my router/firewall stays the same but is very bursty now (expected), I would say it adds around 5 to 10 percent on average, but this is a guestimate.

DNSProxy is limited to max 300 goroutines (configurable), and in my setup that is fine (around 50 clients/devices at the same time). It also assumes/defaults-to a RRL of 20 queries max, which I had to up to 250 to smooth things out and have less retries.

That only port 80/443 is used is not a bad idea/default, most services run over port 443 (around 85% to 90% of all my traffic, same firewall/router).

GeoIP DB is a better combination, but I like the simplicity of "fastest" instead of "proximity", as proximity does not guarantee quickest connection.

I think to make it complete, defining which ports to use based on domain-name (regex) to contain it better would be sweet. For example `^www\.` to port 80/443, `^(smtp|mail|pop3|imap4)\.` for port 25/110/143 etc... I think it is not hard to come up with a good default. I just checked, last 24 hours on my gateway, the number of unique ports connected to was 12. Also to have an option to ignore it for some domains, or just enable it for certain is not bad to have more control.

The latency on the first/virgin query (uncached) is a bit more (in my case between 3 and 10ms added on average), then without the connect-check, but people (including me) don't notice.

I am with you, I was expecting way worse results... :-)

**Comment by folbricht** [comment]
I do like the idea of dynamically configuring the port based on the query name. That's definitely a good idea, though I have to think about what the config structure would look like for this, perhaps similar to a router. We'd also need to make the timeouts and concurrency configurable.

Actually, thinking about it a bit more, we could have a small component that does the speed test with one (or multiple) fixed port numbers and a router component in front to determine when/if which one of those is used. Keeps the complexity down.

**Comment by cbuijs** [comment]
Like that a lot actually.

**Comment by cbuijs** [comment]
Just as extra info, see below:
https://github.com/AdguardTeam/dnsproxy/issues/139

**Comment by cbuijs** [comment]
Actually have a good use-case for this. I recently installed Satellite Internet (StarLink, it is fab!), where latency and fluctuation is more of a thing as with a landline. Also noticed that "the internet" makes some assumptions where I am, and GEO-IP is just screwed when using Sats.

When I back-end routedns with dnsproxy and the "fastest-addr" feature, things become more latency based in a good sense, connections are setup faster and more snappy. I guess the Geo-IP/Proximity thing and load-balancers are not taking into account sat-internet (yet).

Just as note and info.

**Comment by folbricht** [comment]
That's actually a good use-case. As for implementing this, I'm thinking of relying on other things routedns provides quite heavily (like routers and caches). So I'd imagine a chain like this could work:

client -> cache -> router -> fastest-tcp -> upstream

In this setup the `fastest-tcp` component would perform the TCP speed test for every query it receives, and it'd rely on the cache to de-dup requests for the same name. Simplifies the logic that way. Using it without cache would be quite slow though.

About the A record filtering, should it only return the one fastest? Or re-order the A records, putting the fastest at the top,

**Comment by folbricht** [comment]
There's a first implementation on the `issue-149` branch. Done very little testing with it so far, so if you'd like to try it out that'd be much appreciated.

Example config below, combined it with a cache to make it perform a bit better. 
```toml
[listeners.local-udp]
address = "127.0.0.1:53"
protocol = "udp"
resolver = "fastest-cached"

[groups.fastest-cached]
type = "cache"
resolvers = ["tcp-probe"]

[groups.tcp-probe]
type = "fastest-tcp"
port = 443
resolvers = ["cloudflare-dot"]

[resolvers.cloudflare-dot]
address = "1.1.1.1:853"
protocol = "dot"
```

Let me know what you think. Also, the naming can still be changed. It's `fastest-tcp` for now, but I suppose that something like `probe-tcp` would work as well.

**Comment by cbuijs** [comment]
Testing it now, seems to work. I will do some measurements and logging to see how it works and compares to DNS-Proxy as reference as I used/using that as well.

**Comment by cbuijs** [comment]
Looking good so far, it seems to have the same results for clients as with dnsproxy. Maybe some more logging on the probing it self, it no just says "probing 4 ips" and returns the fastest, maybe logging the probes itself, and show which IP was selected to return? Also add which port was probed. And when things time-out or do not respond to the probe and returning the whole answer because cannot determine fastest.
Will keep it running for now as is, if something pops up, I let you know.

**Comment by cbuijs** [comment]
BTW, a thought: Placing this right might need some documentation. If used in conjunction with `filter = true` on a` response-blocklist-ip`, it can have some weird results for example when:

- Number of IP's returned in the DNS answer = 4
- Fastest IP is 1.2.3.4
- 1.2.3.4 if filtered down the line
- Empty answer as result

To counter this, maybe have a configurable option to test ALL ip-addresses and not only return the quickest response. In order of RTT or in order of the connections are made. So the result will have all answers, sorted/ordered in order of fastest to slowerst.

This is much bigger/costly processing wise, but I do see some cases to have it as a configurable option where the current version (only fastest one) being default.

**Comment by cbuijs** [comment]
@folbricht 

Just FYI: Running more than 36 hours now with this feature on, and no issues/errors whatsoever, besides some minor side-effects/wishes mentioned earlier/above.

**Comment by folbricht** [comment]
There's now a `wait-all` boolean flag to make it wait for all probes to finish before returning a sorted list. Just keep in mind that this will be slower on the first lookup since it has to wait for all of them.
```toml
[groups.tcp-probe]
type = "fastest-tcp"
port = 443
wait-all = true
resolvers = ["cloudflare-dot"]
```

Also there's more logging for this now, telling you how long every probe took if you turn on debug logging.

Good point on the documentation when using a filter as well. I still have to write something up for this feature.

**Comment by cbuijs** [comment]
Testing it now, so far so good (running a couple of hours). The slow-down is negligible with a cache in front of it. I have no reason to disable it for now from that end.

**Comment by cbuijs** [comment]
Maybe another extension to this, set/modify the TTL on the returned records when probing was successful.

Either can be set higher or lower values when needed to influence the behaviour of the cache on these.

As most of the decision-making is already done (more than one record, and only A or AAAA), having a `routers`, ttls construct seems to be clunky, and misses the factor of knowing that probing was actually done or not.

Just a wild idea, not a MUST, but makes sense I think. Would use same values as `ttl-modifier`.

**Comment by folbricht** [comment]
I added an new `success-ttl` option to the group, this will let you set the TTL on successful lookups and cache them for longer.

```toml
[groups.tcp-probe]
type = "fastest-tcp"
port = 443
success-ttl=1800 # Cache successful lookups for 30min
resolvers = ["cloudflare-dot"]
```
Also rebased on master so you have all the the other features available as well. Let me know if that works.

**Comment by cbuijs** [comment]
Works as expected, nice one! Thanks!

**Comment by folbricht** [comment]
Merged in https://github.com/folbricht/routedns/pull/155

**Comment by cbuijs** [comment]
Not re-opening, just wondering... Would it be better to use ICMP (Ping) instead and use the RTT of that? It is broader then just assuming one kind of service?

**Comment by folbricht** [comment]
Using ICMP may not work as well. That's because it's frequently treated differently by network devices or blocked altogether. Trying the (assumed) destination port with the same protocol is likely going to work better.

Wrt having multiple ports, have you tried putting something like a `fastest` group in front of a couple of `fastest-tcp`? You could specify one of the `fastest-tcp` with port 80 and one with 443? It's definitely more complex to configure, but also more flexible since you could build the right failover behavior yourself.

**Comment by cbuijs** [comment]
Will try the fastest group suggestion. Kind of covers what I am trying to achieve. Thanks for the suggestion!

**Comment by cbuijs** [comment]
Just for reference, came up with below, which works very good actually:

```
[groups.tcp-probe-web]
type = "fastest"
resolvers = ["tcp-probe-80", "tcp-probe-443"]

[groups.tcp-probe-80]
type = "fastest-tcp"
port = 80
wait-all = true
resolvers = ["tcp-probe-dedup"]
success-ttl-min = 30

[groups.tcp-probe-443]
type = "fastest-tcp"
port = 443
wait-all = true
resolvers = ["tcp-probe-dedup"]
success-ttl-min = 30

[groups.tcp-probe-dedup]
type = "request-dedup"
resolvers = ["doh-internet"]
```
