### ISSUE TITLE
Typo in "response-collapse"

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#151]
https://github.com/folbricht/routedns/blob/59325942d92314af2adef4c9474c6f1e6c525591/response-collapse.go#L49

Typo: `respose` missing an "n" and needs to be `response`.

**Comment by folbricht** [comment]
Fixed in https://github.com/folbricht/routedns/commit/a5088b1b5619084ff7022a6bc210ef6acc0b2904, thank you
