### ISSUE TITLE
Error:  Error="dtls fatal: invalid private key type"

### ISSUE THREAD

**Issue by charlieporth1** [folbricht/routedns#156]
I seem to be getting this error only for DTLS 
DoT DoQ DoH UDP and TDP all work fine 
error="dtls fatal: invalid private key type"
The Key is in RSA format
The config is 
```
[listeners.local-dtls]
address = ":853"
protocol = "dtls"
resolver = "dns-cached"
server-crt = "/etc/letsencrypt/live/example.com/fullchain.pem"
server-key = "/etc/letsencrypt/live/example.com/nopassword.key"
```

**Comment by folbricht** [comment]
The error seems to come from https://github.com/pion/dtls/blob/master/config.go#L178-L191 which suggests it thinks there maybe a DSA key in the chain. Hard to say without looking at the cert/key. Can you reproduce the issue using test keys from https://github.com/folbricht/routedns/tree/master/testdata ?

**Comment by charlieporth1** [comment]
> The error seems to come from https://github.com/pion/dtls/blob/master/config.go#L178-L191 which suggests it thinks there maybe a DSA key in the chain. Hard to say without looking at the cert/key. Can you reproduce the issue using test keys from https://github.com/folbricht/routedns/tree/master/testdata ?

Yes, I was able to get the same result. I'm running Ubuntu Server 20.04 if that helps.
I ended up installing the package from master as well

**Comment by charlieporth1** [comment]
this was the lines from my key that prove its RSA as well
-----BEGIN RSA PRIVATE KEY-----
*******************************************
-----END RSA PRIVATE KEY-----

**Comment by folbricht** [comment]
Yeah, I see that even in my examples I had to use an EC key to get it working. If you use `server-ec.crt` and `server-ec.key` from https://github.com/folbricht/routedns/tree/master/cmd/routedns/example-config it'll work just fine. There must be some kind of limitation in DTLS, I'll take a look at that.

**Comment by folbricht** [comment]
Ah, RSA support was added in 2.0.9 while routedns is using 2.0.8. Easy fix

**Comment by folbricht** [comment]
There's a fix for it on the `update-dtls` branch if you want to try it out

**Comment by charlieporth1** [comment]
> There's a fix for it on the `update-dtls` branch if you want to try it out

Thx

**Comment by charlieporth1** [comment]
It looks like this fixes it. You should be good to merge master

**Comment by folbricht** [comment]
Merged https://github.com/folbricht/routedns/pull/157, thanks for trying it out
