### ISSUE TITLE
Just return SERVFAIL when receiving SERVFAIL for round-robin/fail-rotate/fail-back and random groups

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#161]
For the `round-robin`, `fail-rotate`, `fail-back` and `random` group types. The failover or next resolver will be used when no answer is received (timeout), which is fine, but also when a SERVFAIL is returned.

When all resolvers return SERVFAIL, which is a factual (and a valid) ANSWER you get from a DNS Server, this are unnecessary cycles and multiplies the error basically. 

SERVFAIL is actually an answer, the DNS Server queried determined there is an issue (DNSSEC validation failed for example). This is fine to relay back, no need to "failover" to the next resolver.

I would like to suggest to add a config-option to only go to next resolver when there is no answer/timeout. I still see a case to failover to the next resolver. Maybe together with a "timeout" one to determine how long to wait before on no answer to try the next resolver.

Example (`servfail-failover`):

```
[groups.failover-resolver]
type = "fail-back"
servfail-failover = false # Just relay the SERVFAIL response
timeout = 3 # Seconds to wait on an answer before trying next resolver
resolvers = ["google", "quad9", "opendns"]
```

See also #99 .

**Comment by iamsurfing** [comment]
Agree. I must use 3 groups to block domain. If upgrade, I can use 2 groups to block domain.

 [groups.remove-domain]
  type="response-blocklist-name"
  resolvers=["dns1"]
  blocklist-resolver="dns-removed"
  blocklist-format="domain"
  blocklist=[
  ]

  [groups.dns-removed]
  resolvers=["dns3","dns2"]
  type="fastest"

  [groups.dns]
  resolvers=["remove-domain","dns-removed"]
  type="fastest"

**Comment by folbricht** [comment]
Looks similar to https://github.com/folbricht/routedns/issues/99 where that behavior was changed to what it is now. Seems like we do need an option to either treat SERVFAIL as failure (and rotate), or to pass it through as a valid response. Any thoughts on a good name for the flag? Maybe `servfail-pass = true`?

**Comment by cbuijs** [comment]
Thumbs up for `servfail-pass = true`, might even consider it as default to be closer to how other DNS software works by default.

**Comment by cbuijs** [comment]
Looks like when DNSSEC fails, a SERVFAIL is the standard answer, which will kick off a round through the failover servers and fails after each other as validation will fail on all of them.

Just as "case".

**Comment by folbricht** [comment]
I do agree that we need a flag to control this behavior. Just reluctant to change the default. Should be able to find some time this weekend

**Comment by cbuijs** [comment]
No Hurry, it is fine to keep the default and document when it is handy to use servfail-pass (due to DNSSEC and repetitive behaviour which is inefficient, like using the same DNS provider among all servers).

**Comment by folbricht** [comment]
You can find a first implementation on the `issue-161` branch. A few notes:

- I did in the end agree to change the default and not consider SERVFAIL an error. It was just too messy not to. Instead there's a new flag to re-enable the old behavior if necessary

- `round-robin` doesn't actually have any failover logic, didn't touch this one

- `fail-back` and `random` now have the `reset-after` time (seconds) exposed, giving you more control over how long things are considered bad before they're retried. Unrelated, but I was in that code anyway.

- `fail-back`, `random`, `fail-rotate` now have a `servfail-error` flag which when set to `true` will treat any SERVFAIL response as an error. Without it, SERVFAIL is simply returned as a valid response.

Anyone care to test this? Basically this should give you the old behavior:

```toml
[groups.my-failback-group]
type = "fail-back"
resolvers = ["company-dns", "cloudflare-dot"]
servfail-error = true
```

While without this flag, any SERVFAIL is now passed through, not triggering a failover.

**Comment by cbuijs** [comment]
I did a quick test, both just fault and dnssec-fail tests and seems to work as intended. Speeds up things quite a lot when an error occurred. Seems when it takes longer, other time-outs and errors in the layers/apps on top get triggered, and now not, or less.

Will run this for 24 hours and report back.

**Comment by cbuijs** [comment]
So far after 36 hours, thumbs up!

**Comment by charlieporth1** [comment]
For `fail-back` && `fail-rotate` I personally would like to see a `failed-servers-count=`number | all` so that if it returns servfail on the last server then it is a servfail response`

**Comment by folbricht** [comment]
It should currently default to going through all and returning the last error (presumable a servfail). Limiting it to a number less than the available upstream resolver could create some surprising side-effects, especially in the `fail-back` case. I'll need to think about this a bit more.

**Comment by cbuijs** [comment]
@folbricht This was the initial change in #99, right? The change here is that servfail is returned after a certain amount of failover events. I guess the problem is "what to do after", reset back to starts, or continue to continue where left off after the next SERVFAIL. As we are in a "fail" already, right?

**Comment by folbricht** [comment]
Yes, it could be quite confusing, so if you had something like 5 upstream resolvers, and set the number of failovers to 2, it's not quite clear what to expect in that case. I do think the change is good as-is for now, we could deal with adding a limit to the failover operations separately. Also keep in mind that it's already possible to stack the failover-groups, giving at least some flexibility to configure the desired behavior.

**Comment by folbricht** [comment]
Merged https://github.com/folbricht/routedns/pull/166 to provide config for how to handle SERVFAIL responses in failover-groups
