### ISSUE TITLE
Add regex formatting / standard type to documentation 

### ISSUE THREAD

**Issue by charlieporth1** [folbricht/routedns#162]
Add regex formatting / standard type to documentation. Regex type being POSTFIX, Javascript Perl, Go, Python or custom. I was assuming is postfix I could be wrong. If you tell me the type of regex standard. I would gladly fork it and make a PR

**Comment by folbricht** [comment]
It'd be this one https://golang.org/pkg/regexp/ which says
> The syntax of the regular expressions accepted is the same general syntax used by Perl, Python, and other languages. More precisely, it is the syntax accepted by RE2 and described at https://golang.org/s/re2syntax, except for \C. For an overview of the syntax, run ...

So basically RE2 as per https://github.com/google/re2/wiki/Syntax. If you could make a PR that'd be much appreciated.
