### ISSUE TITLE
Interesting approach to determine if a DNS request is malicious or not

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#169]
See here:
https://navytitanium.github.io/DNSMasterChef/
https://github.com/NavyTitanium/DNSMasterChef

In short:

- Query multiple public DNS for the same query
- If all gave valid answers back, or in the same realm/asn/subnet/etc, answer: Safe
- If there is a difference between the answers (check if same ASN): Potential Unsafe
- When one or more provide back a answer indicating a bad answer: Unsafe

With above, DNS pressure/traffic would be high, but the benefit would be utilizing more then one provider for safe answers potentially catches more. caching will help of course.

Not a feature request here, but I think this is not hard to build as a group based on what is already there. More of a discussion topic.

The other end would be training an human-assisted ML (basically input/source would be the many filter-lists already available), with bad/good answers and potential predict this recognizing the patterns. Same for homographic, DGA, Charachter-Frequency and other fun stuff.

My point is, maybe there is a hidden security side of RouteDNS that could be highlighted ;-).

**Comment by folbricht** [comment]
Some interesting ideas for sure. It would be nice if there was some other API or module that could provide data on reputation etc. That may be more reliable than querying multiple upstream providers. The information that can be gleaned from DNS responses alone is limited. Providing a module to interface with something else would be quite doable though. Just comparing responses could fall over when the providers use GEOIP routing.

On the security-front, I think the first thing that would be a win is a DNSSEC validator (https://github.com/folbricht/routedns/issues/123). I'm looking at that at the moment, but given the complexities, getting that right isn't trivial.

**Comment by cbuijs** [comment]
These I regularly use for classification/categorization:

https://www.klazify.com
https://website-categorization.whoisxmlapi.com/api
https://www.webshrinker.com/apis/

But if it just for safety, integration with Google might be a good idea (anyway):
https://developers.google.com/safe-browsing

Most browsers use this already, but why not limit ourselfs to browsers ;-).

I agree on DNSSEC as a good first step, this makes DNS save. The other/above "features" are more filtering content related using DNS as vehicle of course.

**Comment by cbuijs** [comment]
Just "FYI" piece, closing.
