### ISSUE TITLE
UDP resolver should fallback to TCP on truncation.

### ISSUE THREAD

**Issue by mikhirev** [folbricht/routedns#170]
Hi!

This issue is about the same as #93, that was not properly fixed in fact.That "fix" just set EDNS buffer size to 4096 that does not completely prevent truncation but also introduces potential problems because of possible packet fragmentation.

- According to [DNS flag day 2020 recommendations][1], the minimum safe size is 1232 because it prevents fragmentation in most networks.
- Some servers, e.g. 1.1.1.1, ignore EDNS buffer size in request and truncate all large messages (bigger than 1232 in case of 1.1.1.1). You may check it with a `TXT` request for `test.knot-resolver.cz.`.
- [RFC7766][2] says:
  > - Recursive server (or forwarder) implementations MUST support TCP so that they do not prevent large responses from a TCP-capable server from reaching its TCP-capable clients.

UDP resolver should check the `TC` flag in answers and fallback to TCP if it is set. I also suggest to make EDNS buffer size configurable and set it to 1232 by default.

[1]: https://dnsflagday.net/2020/?#message-size-considerations
[2]: https://datatracker.ietf.org/doc/html/rfc7766#section-5

**Comment by mikhirev** [comment]
This issue also affects DTLS resolver that should also have a fallback alternative. However [RFC8094] does not specify an exact fallback protocol:

> For Strict Privacy, the client MUST only send a new DNS request for the same resource record over an encrypted transport (e.g., DNS over TLS [RFC7858]). Clients using Opportunistic Privacy SHOULD try for the best case (an encrypted and authenticated transport) but MAY fall back to intermediate cases and eventually the worst case scenario (clear text) in order to obtain a response.

So it would be nice to provide a configuration option to set a custom resolver as a fallback for DTLS resolver.

[RFC8094]: https://datatracker.ietf.org/doc/html/rfc8094#section-5
[RFC7858]: https://datatracker.ietf.org/doc/html/rfc7858

**Comment by folbricht** [comment]
There's a few things we should handle separately:

### Failover to TCP

Not sure that routedns is the right place to do this. It should be initiated by the client over TCP, and the forwarder should support it (which routedns already does). The issue with doing it in the forwarder is that the client sent the query over UDP, so the response has to come over UDP as well. If routedns gets the full response over TCP from the server and then tries to build the UDP response for the client, it might still be too large. It could be implemented of course, in like a dedicated element that reacts to the TC flag and switches to a different resolver. That way the failover path could be any other protocol. But it may still not be the right thing to do in all cases.

### Configuring EDNS0 buffer size

This makes perfect sense. It should be configurable on the resolver element, I'll get that in.

### DTLS failover

I'll need to find out what the library does when this happens. Depending on what that looks like, I could add something that forwards to another resolver in that case. Have you tried it?

**Comment by mikhirev** [comment]
> Not sure that routedns is the right place to do this. It should be initiated by the client over TCP, and the forwarder should support it (which routedns already does). The issue with doing it in the forwarder is that the client sent the query over UDP, so the response has to come over UDP as well.

Do you mean that I always need to configure a UDP listener to use a UDP resolver and a TCP listener to use a TCP resolver? Why? I thought that routedns is designed for flexibility. What if I want to use a cache? Should I configure separate caches for UDP and TCP? Why to waste memory for truncated messages?

> If routedns gets the full response over TCP from the server and then tries to build the UDP response for the client, it might still be too large.

This can happen even with UDP if the client's buffer size is smaller than routedns' buffer size. The UDP listener should always check this and set a TC flag if this happens. Doesn't it do so?

BTW if, vise versa, the client's buffer size is bigger than routedns' one and routedns received a truncated answer, this does not mean that the answer cannot fit the client's buffer size. So routedns could (and should, I think) connect to upstream resolver via TCP to get the answer and forward it to the client via UDP, if possible, without forcing it to establish a TCP connection.

> ### DTLS failover
> 
> I'll need to find out what the library does when this happens. Depending on what that looks like, I could add something that forwards to another resolver in that case. Have you tried it?

No, I have not tried it and I'm not aware of public resolvers providing DNS over DTLS. I mentioned DTLS only because it has the same restrictions as plain UDP.

**Comment by folbricht** [comment]
Yes, ideally you should have 2 listeners so clients have something to retry with. Those can both go through the same pipeline though. I did however realize that truncation wasn't well handled before so I put something on the `issue-170` branch. You can now define a retry resolver, so basically if your primary is UDP or DTLS, you can set another one of any type to be used when the primary returns a truncated reply. This should be the most flexible way to configure it, rather than hard-coding it to just plain TCP. Also, you can now set the EDNS0 UDP size with `edns0-udp-size = 1232` on the UDP (or DTLS) resolvers.

An example of how to put it all together and combine it with a cache is here: https://github.com/folbricht/routedns/blob/issue-170/cmd/routedns/example-config/truncate-retry.toml

It should do the same with DTLS though I haven't tested that part. Feel free to try it out from the branch. It should be complete, but there could be bugs.

**Comment by mikhirev** [comment]
> You can now define a retry resolver, so basically if your primary is UDP or DTLS, you can set another one of any type to be used when the primary returns a truncated reply. This should be the most flexible way to configure it, rather than hard-coding it to just plain TCP.

This sounds reasonable, however this makes a typical configuration a bit complicated and obscure for a user who is not very familiar with DNS and UDP. Two resolvers and one group need to be configured to communicate with a single server…

**Comment by folbricht** [comment]
Yup, there sure is extra complexity in this, but it's also the most flexible. I'm not sure if there's a simple alternative. Having the UDP resolver attempt to use TCP doesn't seem great. And there isn't really an obvious faillback for DTLS. Ideally, most people should be using DoT or DoH as upstream anyway and don't need to deal with the intricacies of UDP DNS. Most of the examples use one of those too, and I'll make sure the ones that do use upstream UDP handle with truncation properly.
