### ISSUE TITLE
Question: I know other code but not Go....

### ISSUE THREAD

**Issue by charlieporth1** [folbricht/routedns#172]
Question: I know other code but not Go. I was thinking if you want a code reviewer for PRs I could do that with a basic understanding of Go itself just not a high functioning programmer.

**Comment by folbricht** [comment]
Another set of eyes is very welcome. Appreciate the help. Most PRs should be rather straightforward. If you like, I'll assign them to you.

**Comment by charlieporth1** [comment]
That would be great!

**Comment by folbricht** [comment]
Sent a Github invitation which you need to accept before I can assign PRs it seems.
