### ISSUE TITLE
Blocklist duplicated domain filtration / unique sort and remove.

### ISSUE THREAD

**Issue by charlieporth1** [folbricht/routedns#175]
Blocklist duplicated domain filtration / unique sort and remove from memory. I've noticed after 3 hours of run time route used 4.2GB of RAM

**Comment by folbricht** [comment]
Do you have an example config that'll do this? And how large is the blocklist?

**Comment by charlieporth1** [comment]
Sure its a systemd process that's how I know the size. 
I'm going to create a private repo with the example and invite you

**Comment by charlieporth1** [comment]
My bad didn't mean to open and reclose

**Comment by folbricht** [comment]
Thanks, and wow, this must be the most complex routedns configuration I've seen. Updated a few things like paths, listen IPs and certs and got it running. So far it's behaving correctly. Does mem usage only grow under load? When do you see it happen?

It started up using 130MB for me, will keep it running and monitor for a bit

**Comment by charlieporth1** [comment]
I believe so. I've found it grows randomly I just had it running for 4 hours and only 130 MB
Right now its been running for an Hour and 2.5GB. And oddly enough it only does it on higher memory servers. 4. GB or more 
I've got 2 servers with 4 GB or more. I've only seen it grow past the GB range after a couple of hours but you will know when it does because the memory will increase gradually but not reach the limit until later. After 30 minutes in most cases you'll see Route use 500-900 MB if the leak is happening. I'm not sure its a memory leak though because it doesn't use all of my ram.
The most I've seen it use is 4.2 GB on a 6 GB server. Try restarting the systemd process until it you get a steady increase in RAM usage every second ~ 0.5 MB ~ 3 MB increases 
![image](https://user-images.githubusercontent.com/13573364/128644644-7a6b4141-3691-4c55-ab3e-305a3b63c45f.png)

**Comment by folbricht** [comment]
Could you check your logs to see if it's maybe related to a failure to load the blocklist? With the current blocklist I get
```
Error: ctp-dns-blocklist: error parsing regexp: missing closing ): ...
```
So perhaps that can only be seen when there's some kind of failure to refresh the list.

**Comment by charlieporth1** [comment]
Yes, I had an error with one of the blacklists. It should be fixed. It was a broken regex. That's unrelated

**Comment by folbricht** [comment]
No luck reproducing it here, had it run for 5+ hours in systemd and still taking just 130M. Can keep trying the next few days, but if you see anything that might trigger it, let me know

**Comment by charlieporth1** [comment]
Will do.

**Comment by iamsurfing** [comment]
@folbricht 

I noticed you but it seems like you are not care about it.

How to reproduce it?
Block response after TLS client-hello.

How to solve it?
like this.
https://github.com/iamsurfing/routedns/blob/master/lockduplicaterequest.go

**Comment by iamsurfing** [comment]
@charlieporth1 
You can try this.
First, modify `routedns\cmd\routedns\main.go`

`\\switch g.Type {`
`    case "lock-duplicate-request":`
`		if len(gr) != 1 {`
`			return fmt.Errorf("type lock-duplicate-request only supports one resolver in '%s'", id)`
`		}`
`		resolvers[id] = rdns.NewlockDuplicateRequest(id, gr[0])`
`\\}`

Second, add this file to root folder.
https://github.com/iamsurfing/routedns/blob/master/lockduplicaterequest.go

Third, add this block both **before cache** and **after cache**.
`  [groups.example]`
`  type="lock-duplicate-request"`
`  resolvers=["example"]`

If it can solve your problem, you can pull request.

**Comment by folbricht** [comment]
I've run the config for days now, though without querying/using it. Not seen anything like that spike in memory. It stays around 130MB for days. So perhaps it really is related to what queries are being made, not to updating the blocklists alone.

@iamsurfing I don't see how that code would have anything to do with the original issue. All that's going to do is make queries slower under load, under heavy load it'll even cause memory pressure. That implementation not only locks duplicate queries and serializes them, it also serialized other unrelated queries. Putting a lock around "Resolve()" is not a good idea.

**Comment by iamsurfing** [comment]
@folbricht 
It is a good idea, or you have a better solution.
(It seems that it is not the same issue, but this will cause high-memory-usage, DDoS DNS server and decrease network speed problem.)

![1](https://user-images.githubusercontent.com/16305191/129506177-6148d71b-c28b-4ce0-9275-0d1996eba2d8.png)
![2](https://user-images.githubusercontent.com/16305191/129506188-a5fa35f3-34bf-499d-a795-afbb5b709a5a.png)

**Comment by charlieporth1** [comment]
Sorry for being so late to get this message. I can try this weekend

**Comment by charlieporth1** [comment]
@iamsurfing Is right though I am getting DDOSed

**Comment by iamsurfing** [comment]
@charlieporth1 
DDoS only happen from bad network signal to good.
For example, when your WiFi signal is bad ,DNS request will be stored in socket cache.
Then you move your device to make WiFi signal good, this duplicate request will be sent to DNS server.
However, this can only decrease your network speed and DNS provider do not care about it.

**Comment by charlieporth1** [comment]
@iamsurfing Does include mobile networks? Also is your example client side or server side?

**Comment by charlieporth1** [comment]
@folbricht Quick question I think this might be part of the reason for large memory usage but I've got the cache before the before -- which on a hunch that leads to double caching of some of the items on the blacklist I believe or at lease in theory

**Comment by charlieporth1** [comment]
I am not getting this error anymore closing
