### ISSUE TITLE
Answer incoming requests/queries from same IP address

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#19]
I have 3 IP addresses on my network-interface of my machine/os, I only use the third one with my DNS clients.

When a DNS request comes in on that IP address, the answer is send from the first one (not configured in listeners) and not from the IP address the request comes in on.

Both for IPv4 and IPv6 and happens when only using the port as address `:53`.

Would it be possible to send answers from the same IP as the request/query comes in?

Using Debian 10 Linux as platform/os, and it seems that only UDP traffic is affected (need to test more to make sure though).

**Comment by folbricht** [comment]
Hmm, interesting and unexpected bug. Not tried that before, but it can only really impact UDP. Will need to take a look at how the UDP listener is used again.

**Comment by cbuijs** [comment]
Seen this before, trying to figure out what it was. Can imagine as UDP is stateless.

**Comment by folbricht** [comment]
I'm still unable to reproduce this on a multi-NIC machine. Do you have 3 NICs on your test machine or 2 alias IPs? Might be worth seeing if that can be captured in tcpdump

**Comment by cbuijs** [comment]
It is a single NIC with aliases. And it only happens when using IPv6 as the extra IP's are all IPv6 besides the primary ones. Answers always come from the primary-address while requests come in on the second alias. I will create some logging and setup-info and share this.

**Comment by cbuijs** [comment]
Maybe the "easy" fix here is to be able to specify the outgoing interface/ip on a resolver?

**Comment by cbuijs** [comment]
Cannot replicate this, together with the `local-address` feature, this can be concidered "fixed".
