### ISSUE TITLE
Are ECDSA keys supported?

### ISSUE THREAD

**Issue by charlieporth1** [folbricht/routedns#190]
Are ECDSA keys supported? I'm using one and I seem to have trouble with my Android phone connected to my server without the use of a 3rd party app via DoT, the 3rd party app suggests it's not the key issue but if there is a specific thing I need to do it would help. Any help is appreciated! I'm using Lets Encrypted for certs. I've seen that Cloudflare uses ECSDA and ECprime for the cert for one.one.one.one. But Google uses RSA only for dns.google. I'm trying to navigate away from RSA because RSA is heavy on the CPU. My Chain goes ECDSA RSA RSA which I don't known if that is the problem

**Comment by cbuijs** [comment]
There was a discussion somewhere that EC certs are needed anyway as requirement for DNS-over-DTLS (DoT over UDP basically). I tested that back when it came out as a feature and did work with EC certs. Not sure if the same code is used in the other protocols though.
