### ISSUE TITLE
Issue with the "tcp-fast" when rrset is cname-chain, non-a/aaaa records stripped and qname not used in response.

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#191]
When in use, `response-collapse` does this:

`dig www.youtube.com`:

Collapsed Answer (it is just stripping everything but the address-answers):
```
youtube-ui.l.google.com. 300	IN	A	216.58.208.110
youtube-ui.l.google.com. 300	IN	A	216.58.214.14
youtube-ui.l.google.com. 300	IN	A	142.250.179.142
youtube-ui.l.google.com. 300	IN	A	142.251.36.46
youtube-ui.l.google.com. 300	IN	A	172.217.168.238
youtube-ui.l.google.com. 300	IN	A	142.250.179.174
youtube-ui.l.google.com. 300	IN	A	142.250.179.206
youtube-ui.l.google.com. 300	IN	A	142.251.39.110
youtube-ui.l.google.com. 300	IN	A	172.217.168.206
```

But it should be (name of each record must be the QNAME):
```
www.youtube.com. 300	IN	A	216.58.208.110
www.youtube.com. 300	IN	A	216.58.214.14
www.youtube.com. 300	IN	A	142.250.179.142
www.youtube.com. 300	IN	A	142.251.36.46
www.youtube.com. 300	IN	A	172.217.168.238
www.youtube.com. 300	IN	A	142.250.179.174
www.youtube.com. 300	IN	A	142.250.179.206
www.youtube.com. 300	IN	A	142.251.39.110
www.youtube.com. 300	IN	A	172.217.168.206

```
This was not an issue before, but seems browsers starting recently have become more DNS savvy and start checking this more resulting in DNS resolution problems within the browser. Same issue with recent versions of Chrome, Firefox and Safari.

Not sure if it was working before, but the latest version is not replacing the name of resulting records with the QNAME anymore.

**P.S.** Might actually be a side-effect of using `fastest-tcp`, i will check when I have time.

**Comment by folbricht** [comment]
Hmm, that hasn't changed, and it still seems to work for me. The line of code that would set the name is https://github.com/folbricht/routedns/blob/master/response-collapse.go#L40 and that's been there for a while.

Without `response-collapse` I get
```
;; ANSWER SECTION:
www.youtube.com.	86388	IN	CNAME	youtube-ui.l.google.com.
youtube-ui.l.google.com. 3599	IN	A	142.250.69.206
youtube-ui.l.google.com. 3599	IN	A	142.250.217.78
youtube-ui.l.google.com. 3599	IN	A	172.217.14.206
youtube-ui.l.google.com. 3599	IN	A	142.250.217.110
youtube-ui.l.google.com. 3599	IN	A	142.251.33.78
youtube-ui.l.google.com. 3599	IN	A	172.217.14.238
youtube-ui.l.google.com. 3599	IN	A	142.251.33.110
```
And with `response-collapse` I see this which looks correct
```
;; ANSWER SECTION:
www.youtube.com.	300	IN	A	172.217.14.206
www.youtube.com.	300	IN	A	172.217.14.238
www.youtube.com.	300	IN	A	142.250.69.206
www.youtube.com.	300	IN	A	142.251.33.110
www.youtube.com.	300	IN	A	142.251.33.78
www.youtube.com.	300	IN	A	142.250.217.78
www.youtube.com.	300	IN	A	142.250.217.110
```

Can you double-check your config? I can't think of another element that could cause this side-effect.

**Comment by cbuijs** [comment]
It seems to be fastest-tcp related. When I disable all is good.

**Comment by cbuijs** [comment]
It is `tcp-fast`. When i take that out of the loop, all works fine. Looks like the `tcp-fast` only returns the tested/fastest IP's without changing the name when it is preceded by a `cname` chain, the cnames are just stripped off. I think not stripping anything and only re-sort the A/AAAA records and leave as is, is the way to go for `tcp-fast`. The response-collapse can be used for that if needed/wanted.

**Comment by folbricht** [comment]
Thanks for debugging. I'll look into fixing that this weekend.

**Comment by folbricht** [comment]
Got a proposed fix on the `issue-191` branch. This preserves all non-IP records and just re-orders the list.

**Comment by cbuijs** [comment]
The fix works great! Also in combination with `response-collapse`. Thanks for the quick fix!
