### ISSUE TITLE
Support for EDNS Client Subnet (ECS)

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#2]
Hi,

Love RouteDNS!

How about support for EDNS Client Subnet (ECS), e.g. manipulate/augment/overwrite/add/remove the ECS from the queries going out? I want to overwrite it because of CDN's usage and also for privacy concerns.

Thanks, keep up the great work!

-Chris.

**Comment by folbricht** [comment]
Looks like the DNS library would support it. So it's definitely possible. Couple of issues I need to deal with:
1) Read up on ECS to understand what needs to be done
2) Find an elegant way of describing the operations in the config file. Suspect it's easier in code than in config.

The latter can be tricky. Thinking of either introducing an edns-manipulator element that could be added to resolving chains, or multiple more specific elements doing just one thing each. Any suggestions are welcome.

**Comment by cbuijs** [comment]
I would add it to "Resolvers" option and have basically four options:

- Ignore: Don't do anything (Default)
- Delete: Remove existing ECS from the query received.
- Add: Add the client-ip as ECS or able to just set/override it in the config, this would override any ECS (if any) from the query received or add it when none.
- Privacy: Tone down the ECS on number of bits (IPv4 and IPv6). For example, if set to /24 for IPv4, the ECS would go from "213.123.123.66/32" to "213.123.123.0/24". Defaults should be /24 for IPv4 and /64 (or /48) for IPv6.

-Chris.

**Comment by folbricht** [comment]
You can find a first implementation of this on the https://github.com/folbricht/routedns/tree/ecs-modifier branch. Examples in the readme.

It was a bit rushed so quite possible I missed something. Let me know how that works for you.

**Comment by cbuijs** [comment]
Works as expected, great addition!!!

**Comment by cbuijs** [comment]
BTW, it seems you cannot go from groups to a router object? Seems to work before the ECS addition or this version.

**Comment by folbricht** [comment]
Merged in https://github.com/folbricht/routedns/pull/8
