### ISSUE TITLE
Dot domains are causing blacklisted domains to be allowed 

### ISSUE THREAD

**Issue by charlieporth1** [folbricht/routedns#200]
`.com` and `.co` are allowing blacklisted items like `ad.intl.xiaomi.com` to be allow listed when it should be compared by domains length as to who gets the priority over each other

**Comment by folbricht** [comment]
Do you have an example. The allowlist items should override the blocked items, so `.com` seems to work, but `.co` shouldn't so there could be a bug

**Comment by charlieporth1** [comment]
@folbricht 
```
time="2021-12-26T11:21:55-06:00" level=debug msg="cache-miss, forwarding" client=174.53.130.17 id=ctp-dns-cached qname=sdkconfig.ad.intl.xiaomi.com. qtype=A resolver=ctp-dns-min-ttl
time="2021-12-26T11:21:55-06:00" level=debug msg="matched allowlist, forwarding" client=174.53.130.17 id=ctp-dns-blocklist qname=sdkconfig.ad.intl.xiaomi.com. qtype=A resolver=ctp-dns-fail-back rule=.co
time="2021-12-26T11:
```

**Comment by folbricht** [comment]
Hmm, what type of allowlist did you use for this? Was it the regex kind? If not, then this looks indeed like a bug

**Comment by folbricht** [comment]
Yup, the `tld-whitelist.list` would need to be terminated with $ to work, but you probably don't want it to be a regex list. A regular one is going to be much faster anyway

**Comment by charlieporth1** [comment]
@folbricht that's less so the problem. more so that 

whitelisted `.com` is allowing a blacklisted item which is `ad.intl.xiaomi.com.`
which the blacklisted item should override the `.com` due to length of the blacklisted item
```
time="2021-12-26T13:55:53-06:00" level=debug msg="cache-miss, forwarding" client=10.128.0.9 id=ctp-dns-cached-front qname=ad.intl.xiaomi.com. qtype=A resolver=root-router
time="2021-12-26T13:55:53-06:00" level=debug msg="routing query to resolver" client=10.128.0.9 id=root-router qname=ad.intl.xiaomi.com. qtype=A resolver=ctp-dns-cached
time="2021-12-26T13:55:53-06:00" level=debug msg="cache-miss, forwarding" client=10.128.0.9 id=ctp-dns-cached qname=ad.intl.xiaomi.com. qtype=A resolver=ctp-dns-min-ttl
time="2021-12-26T13:55:53-06:00" level=debug msg="matched allowlist, forwarding" client=10.128.0.9 id=ctp-dns-blocklist qname=ad.intl.xiaomi.com. qtype=A resolver=ctp-dns-fail-back rule=.com

```

**Comment by folbricht** [comment]
The length doesn't play a role here. Anything that matches in the allowlist will be let through, regardless of length. It's more flexible that way. What are you trying to do? I believe it can be solved with the current implementation too. If you're trying to only allow some TLDs, you could put a blocklist in front which blocks everything, and allows only those TLDs

**Comment by charlieporth1** [comment]
I think I get what your saying
