### ISSUE TITLE
Ability to force DNS client to use TCP (set TC bit)

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#208]
See also #205 and https://github.com/folbricht/routedns/issues/205#issuecomment-1027650690.

To mitigate some common DDOS attacks, which mostly rely on UDP and Spoofing, a feature that kicks in based on particular load, that the DNS clients can be told to switch to TCP. This can be done by the DNS Server (RouteDNS) answering with the `TC` (Truncate) bit set. It annulls spoofing and takes the punch out of the attacks relying on it (almost all DNS based attacks).

I think having a `static-responder` (like the `drop` one), where you can set this is enough to mitigate and use it together with the `rate-limiter` for example.

Would look like this as example:
```
# Rate-Limiter
[groups.rrl]
type = "rate-limiter"
resolvers = ["internet-resolver"]
limit-resolver = "set-tc"
requests = 100
window = 120
prefix4 = 24
prefix6 = 56

# Respond with TC bit set
[groups.set-tc]
type = "truncate"
```

Result will be that a query of a DNS client will be responded to with an "Try again using TCP". Two effects, traffic will go down a bit as only legitimate clients (unspoofed ones) can connect, and when TCP is used, more mitigation/standard features (congestion control, queing, etc) of the TCP stack will kick in as standard and can be used as well.

See also: https://help.fortinet.com/fddos/4-3-0/FortiDDoS/Understanding_FortiDDoS_DNS_Attack_Prevention.htm

**Comment by cbuijs** [comment]
I have thrown something together, see PR #209

**Comment by cbuijs** [comment]
Tested it, and works:

```
dig @<censored> -p 9053 www.paypal.com
;; Truncated, retrying in TCP mode.

; <<>> DiG 9.16.23 <<>> @<censored> -p 9053 www.paypal.com
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49979
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.paypal.com.			IN	A

;; ANSWER SECTION:
www.paypal.com.		2400	IN	A	151.101.65.21

;; Query time: 10 msec
;; SERVER: <censored>#9053(<censored>)
;; WHEN: Wed Feb 02 11:36:12 CET 2022
;; MSG SIZE  rcvd: 62
```

Used below config to test, basically all UDP queries get an empty answer with TC (truncate) bit set, telling to retry over TCP. The TCP listener resolves anything.

```
[listeners.do53-udp-test]
address = "[::]:9053" # UDP
protocol = "udp"
resolver = "truncate" # Set TC Bit to tell client to try again using TCP

[listeners.do53-tcp-test]
address = "[::]:9053" # TCP
protocol = "tcp"
resolver = "doh-google"

[groups.truncate]
type = "truncate"

[bootstrap-resolver]
protocol = "doh"
address = "https://dns.google:443/dns-query"
bootstrap-address = "8.8.8.8"

[resolvers.doh-google]
protocol = "doh"
address = "https://dns.google:443/dns-query"
```

**Comment by folbricht** [comment]
Noticed this after looking at https://github.com/folbricht/routedns/pull/209 Are there any advantages to having this as it's own element, vs adding flags like that to the static-responder?

**Comment by cbuijs** [comment]
Not sure, this is my first completely uneducated stab at GO and a PR. I just took the (for me) easy route.

Only thing I can think of theoretically is that having it separate probably use less cycles as it is "simpler" and "less code" then the static-responder which has more functionally attached to it. Which might be important in an attack situation where this is used as mitigation?

**Comment by cbuijs** [comment]
Created a more complete version based on `static-responder`, see #211 .
