### ISSUE TITLE
Integrate public-suffix-list

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#216]
See here: https://publicsuffix.org/

Would be nice to have something that when a query comes in, it is validated against this list, and based on configurable policy/settings/block/allow action is taken.

One of the results would be that domains (and sub or parents domains) are actually tested for existence before forwarding, which alleviate the resolution process in general. And have a stricter resolution anyway. Nice side-effect is that private (or non-public) domain queries stay "inside", preventing "leakage".

Example: query for `www.company.doesnotexist` would be forwarded as-is anyway currently. Now with the public-suffix-check it would be dropped/nxdomain/etc immediate (action configurable of course).

See also:
https://github.com/publicsuffix
https://github.com/weppos/publicsuffix-go

P.S.
This kind of can be done using the `blocklist-v2`, and use blocklist-source as "allowlist" using my iana lists. See config-example here (this is how I use it today):

```
[groups.tld]
# Based on / see-also:
# https://data.iana.org/TLD/tlds-alpha-by-domain.txt and 
# https://www.iana.org/domains/root/db
type = "blocklist-v2"
resolvers = ["nxdomain"] # Default NXDOMAIN when the TLD does not exist
blocklist-refresh = 14400
blocklist-resolver = "doh-google" # Forward to google when it is an existing TLD
blocklist-source = [
        {name = "IANA-CCTLD", format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/chris/iana-dot.tld-country-code.list"},
        {name = "IANA-GENTLD", format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/chris/iana-dot.tld-generic.list"},
        {name = "IANA-GENRESTLD", format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/chris/iana-dot.tld-generic-restricted.list"},
        {name = "IANA-INFRATLD", format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/chris/iana-dot.tld-infrastructure.list"},
        {name = "IANA-SPONSOREDTLD", format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/chris/iana-dot.tld-sponsored.list"},
]
```

**Comment by folbricht** [comment]
This is quite a good use-case. Since it can be implemented with an existing blocklist, would we even need a new element? Or just add this case to the docs?

**Comment by cbuijs** [comment]
Fair point.

The syntax of the PubSuffix list is a bit specific, so maybe make `blocklist-v2` accept the syntax? I like this list to be used directly as it is a defacto one, standardized and used by many browsers/apps/etc already as well. So it is very vetted. It is kind of policy based list though, which does more then block/allow, but that is just configuration of how to use it I guess.

I can update my repo with a specific version of it for Routedns (and we can document this in examples).

Alternatively, there is this list:
https://data.iana.org/TLD/tlds-alpha-by-domain.txt

But it does not have the dot at the beginning of the domains to be sub-domain inclusive. Having a format option for this, or a flag to "include subdomains" on `blocklist-v2` might be the quickest way to have the same purpose/effect.

**Comment by cbuijs** [comment]
Below list will be generated every 24 hours from the Publix-Suffix list and will work with `blocklist-v2`:
https://raw.githubusercontent.com/cbuijs/accomplist/master/pubsuffix/routedns.pubsuffix.list

Extra/Updated example (I did **not** extensively tested it yet):
```
[groups.pubsuffix]
# Based on / see-also:
# https://publicsuffix.org/list/
type = "blocklist-v2"
resolvers = ["nxdomain"] # Default NXDOMAIN when the Publix-Suffix does not exist
blocklist-refresh = 14400
blocklist-resolver = "doh-google" # Forward to google when it is an existing Publix-Suffix
blocklist-source = [
        {name = "PUBSUFFIX", format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/pubsuffix/routedns.pubsuffix.list"},
]
```

**Comment by charlieporth1** [comment]
@cbuijs This is kinda what I was talking about in #194 when sorting thru blocklist domains to break domains into categories and make lists smaller and faster by matching `.dev` to a `.dev` not a `.io` for example

**Comment by cbuijs** [comment]
@charlieporth1 not sure if I get/got it correctly (my mistake).

I interpreted #194 as "a faster alternative" to checking/matching for domains against large lists (I actually generate `top-n` lists with active-domains to reduce lists massively for this, see [here](https://github.com/cbuijs/accomplist)).

Above is just making sure what is resolved, actually has an existing TLD/2LD, and if not, just drop the request (with an `NXDOMAIN` for example), and use less resolution cycles and reduce traffic for domains that never would be resolved. Also keeps private/local domains "inside" and prevent leakage for security purposes.

Together with #217 and having a full recursion feature (see #123), and of-course caching, makes the resolution process faster, more efficient which is cool in environments with heavy DNS traffic/requests. As a further elaboration.

I see your point by optimizing the list against a kind of "proof-list" (domain or regex based), when loading and remove any "invalid" or "unusable" TLD/2LD's as well (I think that was the purpose?) making the lists smaller by removing cruft?

**Comment by charlieporth1** [comment]
@cbuijs Less to do with cruft (badly designed right? I had to Google that) And more so to make large amounts of domains processed into a smaller list ctptech.dev getting compared to a list of .dev domains rather than a list of random domains like .io or .com or .net

**Comment by cbuijs** [comment]
Together with my [list](https://raw.githubusercontent.com/cbuijs/accomplist/master/pubsuffix/routedns.pubsuffix.list) and config examples [above](https://github.com/folbricht/routedns/issues/216#issuecomment-1038786922), I think this "feature" is covered.
