### ISSUE TITLE
Feature Request: use DOH path as selection criteria. 

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#234]
Currently there is no way to modify what the path is of a DOH listener. It defaults do `/dns-query`.

It would be nice to be able to modify this, but also based on what path the query comes in on, select a different `resolver`.

**Comment by cbuijs** [comment]
See NextDNS as an example how to utilize it for "identification" purposes, but I think it would be awesome if we can turn into something where based on the identification you can select a resolver (next entity in the chain).

This makes configs based on identification of the query work.

So for DOH usage you could do (as example):

`https://my.dns.tld:443/filtered`: For ad-filtered resolutions
`https://my.dns.tld:443/unfiltered`: For plain/unfiltered resolutions.

Today I do this by having different ports per DOH listener, which is cumbersome, but also potentially a security hazard (more ports open).

See NextDNS documentation (screenshot) on this as example to make this more alive:

![image](https://user-images.githubusercontent.com/6727250/163341257-87eb414f-6583-457c-9678-e0b50856e767.png)

**Comment by folbricht** [comment]
It can see the utility of this. Making the path configurable is pretty simple, but using different resolvers based on path isn't. Not because it's hard to implement, but because it doesn't fit well into the current config structure unfortunately. We'd have to have a map of query-path to resolver in the config to support this.

**Comment by cbuijs** [comment]
Couldn't we just add a parameter "paths" to the DOH listener?

Example:
```
[listeners.doh]
address = "[::]:443"
protocol = "doh"
resolver = "default" # Used when no paths match
paths = [
  {path = "/dns-query", resolver = "default"},
  {path = "/filtered", resolver = "filter"},
  {path = "/unfiltered", resolver = "unfilter"},
]
```
Or is this actually what you were saying?

**Comment by folbricht** [comment]
Yes, that's what I meant. It's doable, I'll try to get to it the next few days. The config is flexible enough to allow filtering on host and/or path, though path is easier for now as using the hostname too would require SNI support in the config as well. The structure above can be expanded to also route based on hostname later.

**Comment by cbuijs** [comment]
Path should be fine. Hostname would mean we could have similar features with DoT/DoQ for example. That was more my thinking.

**Comment by charlieporth1** [comment]
@cbuijs @folbricht 's time is valuable and unfortunately in limited supply which makes. I know `go` to a limited extent and while I would love to see this implemented as well I don't think I can handle all of the requests but I can try as I would like to improve my `go` skills. But if I cannot complete it I think a good alternative which is what I use is NGINX and proxy_pass. I use it for DoH JSON and RFC which passed to Pi-Hole. RFC is from RouteDNS. With PR #239 this should be even easier on the system - which I currently SSL to pass RFC but no SSL on JSON.

**Comment by cbuijs** [comment]
@charlieporth1  That is very similar what I do today, I have front-ended RouteDNS with NGINX. Using different "ports" listening with RouteDNS and let NGINX make the decision which port connect to based on DOH Path and Hostname. One (RouteDNS) port is used for filtered DNS, the other for unfiltered and another for some "basic/light" filtering. As I use a containers (separate), anything I can spin down and don't have to use and make the setup simpler, is my goal ;-).

**Comment by folbricht** [comment]
I found another (possibly more flexible) way of implementing this. The query path is now passed along with the client IP, allowing a router to match on it. You can find a draft implementation on the `issue-234` branch. With this change, a DoH server accepts any path, and you can use a router to send it to the right place like so:
```toml
{ doh-path = "^/dns-query$", resolver = "cloudflare-dot" },
```

**Comment by cbuijs** [comment]
This works great!

One thing, which is actually more related to `routers` in general. For logging purposes, could there be an identifier which route/rule was selected, e.g. the argument(s) that were hit beside the resolver used (which is in there already)?

**Comment by cbuijs** [comment]
Perhaps additional on logging, when a query comes in on `doh`, the doh-path is added to the log-output?

Today it shows this:
`msg="received query" addr="[::]:443" client="192.168.1.10" id=doh-listener protocol=doh qname=www.google.com.`

Add the doh-path so it shows this (example):
`msg="received query" addr="[::]:443" client="192.168.1.10" id=doh-listener protocol=doh doh-path=/dns-query qname=www.google.com.`

Adding `qtype` as well to this would be cool for troubleshooting and log filtering.

**Comment by folbricht** [comment]
I added logging of which route matched in a router (shows the params of the route). Also the DoH listener now logs the query path.

**Comment by cbuijs** [comment]
Looks like it is working as expected, great!

On the routes logging, is seems that the field/info for the `type` (without 's') one is missing, `types` is in there.

**Comment by folbricht** [comment]
That's because internally it just uses `types` so even if the route is given as `type='A'`, it'll turn into an array like `types=['A']` which is the more generic form. The `type` only exists for backwards compatibility.

**Comment by cbuijs** [comment]
Got it, cool. Thanks!

**Comment by cbuijs** [comment]
Running this now for more then 20 hours straight without any issues. Looking great. My thumbs up for the merge.

**Comment by cbuijs** [comment]
Works as expected, please merge if not done already.
