### ISSUE TITLE
Getting this error when building version 1.4

### ISSUE THREAD

**Issue by charlieporth1** [folbricht/routedns#235]
After running `/snap/bin/go  install -v github.com/folbricht/routedns/cmd/routedns`
```
github.com/folbricht/routedns
# github.com/folbricht/routedns
/root/go/src/github.com/folbricht/routedns/dohclient.go:275:9: cannot use dialer (variable of type func(ctx context.Context, network string, addr string, tlsConfig *tls.Config, config *quic.Config) (quic.EarlyConnection, error)) as type func(ctx context.Context, addr string, tlsCfg *tls.Config, cfg *quic.Config) (quic.EarlyConnection, error) in struct literal
```

**Comment by folbricht** [comment]
I can't reproduce this, and in fact your PR fails to build as well (https://github.com/folbricht/routedns/pull/236). Almost looks like you may have some unexpected code changes in your working copy. Make sure it's clean from master

**Comment by charlieporth1** [comment]
Agreed might `rm -rf go dir

**Comment by charlieporth1** [comment]
` /snap/bin/go  install -v github.com/folbricht/routedns/cmd/routedns@master` works but  `/snap/bin/go  install -v github.com/folbricht/routedns/cmd/routedns` does not
