### ISSUE TITLE
Logging: Expand to show which "group" is used.

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#24]
Now in logging we have something like this:

` .... resolver="Blocklist(Multi-Blocklist)"`

Could it be extended which groups/resolver is used by name? For example, I use one group called:

`[groups.Cloaked-Domains]`

I suggest to change current/above logging to (when hit/used):

`.... resolver="Multi-Blocklist(Cloaked-Domains)"`

I suggest the same for the `routers` logging, as if you have a couple of rules in there, the logging becomes unreadable.

**Comment by folbricht** [comment]
Good idea, I can provide the name of each entity, not just groups, to add this to the identifier used in logs.

**Comment by folbricht** [comment]
Is there any value to show additional information such as the size of the blocklist, or actual routes, etc in the ID string?

**Comment by cbuijs** [comment]
I don't think so, during loading of the lists and such: Yes. But for every log-line, not really. Unless it shows something like "hits" (the number of hits the rule got).

**Comment by cbuijs** [comment]
And... when you are on it, maybe expand the logging of allowed/blocked responses from:

`... level=debug msg="blocking response" rule=.trafficmanager.net`

to include the qname of the request?

**Comment by folbricht** [comment]
First implementation on the `issue-24` branch. This adds an `id=` to ever element with the name of it. The goal is to have debug level logs (`routedns -l 5 ...`) show every part of the pipeline.

**Comment by cbuijs** [comment]
Yes, this is making things much easier, also that the resolver name is mentioned now!

**Comment by folbricht** [comment]
Merged in https://github.com/folbricht/routedns/pull/51, any additional fine-tuning can be handled in a new ticket.

**Comment by cbuijs** [comment]
After `id=` and `qname=` it might be handy to include `qtype=` as well?

Now when something happens to an `A` record, but something different to the `AAAA` record of the same `qname`, the logging is not clear (enough) about it.
