### ISSUE TITLE
Error when trying rate-limiter.toml example

### ISSUE THREAD

**Issue by mdavids** [folbricht/routedns#252]
I can't get 'rate-limiter.toml' to work:

`Error: edge between 'cloudflare-rrl' and 'cloudflare-dot' is already known`

https://github.com/folbricht/routedns/blob/4c6085d8494d72beaff1292abd16a57e7373a582/cmd/routedns/example-config/rate-limiter.toml#L10

**Comment by folbricht** [comment]
Thank you. I committed a fix for the example config.
