### ISSUE TITLE
How to test DoH-over-QUIC, I didn't find a client that I can test

### ISSUE THREAD

**Issue by thb007** [folbricht/routedns#255]
How to test DoH-over-QUIC, I didn't find a client that I can test
```
[listeners.local-doh-quic]
address = ":1443"
protocol = "doh"
transport = "quic"
resolver = "cloudflare-dot"
server-crt = "example-config/server.crt"
server-key = "example-config/server.key"
```

**Comment by thb007** [comment]
How to test DoH-over-QUIC, I didn't find a client that I can test

```
[listeners.local-doh-quic]
address = ":1443"
protocol = "doh"
transport = "quic"
resolver = "cloudflare-dot"
server-crt = "example-config/server.crt"
server-key = "example-config/server.key"
```

**Comment by folbricht** [comment]
Are you trying to test doh over quic locally? You can just use routedns as client. There's an example config in `doh-quic-client-local.toml`

**Comment by thb007** [comment]
> Are you trying to test doh over quic locally? You can just use routedns as client. There's an example config in `doh-quic-client-local.toml`

ok , it has been successful

**Comment by thb007** [comment]
I have another question, using "request-dedup" , will it affect the final result of ecs subnet resolution?

**Comment by folbricht** [comment]
It shouldn't, the ECS subnet is part of the key that is used for de-dup. So a similar request with a different subnet will not be de-duped.

**Comment by thb007** [comment]
> It shouldn't, the ECS subnet is part of the key that is used for de-dup. So a similar request with a different subnet will not be de-duped.

good
