### ISSUE TITLE
Can't get the real ip of the client

### ISSUE THREAD

**Issue by liang-hiwin** [folbricht/routedns#260]
When routedns is used as the upstream dns of adguard home, the real ip of the client cannot be obtained. The default client ip obtained is 127.0.0.0/24/0, which is wrong.

**Comment by charlieporth1** [comment]
> When routedns is used as the upstream dns of adguard home, the real ip of the client cannot be obtained. The default client ip obtained is 127.0.0.0/24/0, which is wrong.

This is actually correct due to the nature of the Adguard client. It tunnels all DNS via localhost

**Comment by thb007** [comment]
> > When routedns is used as the upstream dns of adguard home, the real ip of the client cannot be obtained. The default client ip obtained is 127.0.0.0/24/0, which is wrong.
> 
> This is actually correct due to the nature of the Adguard client. It tunnels all DNS via localhost.

However, the parsed ip by appending the subnet mask 127.0.0.0/24/0 is not the location closest to me nor where the server is located, the parsed ip changes randomly, oh my god it's scary, it's not the actual client ip, they are different from real ip.

**Comment by thb007** [comment]
```
func realIP(r *http.Request) (ip net.IP, err error) {
	proxyHeaders := []string{
		"CF-Connecting-IP",
		"True-Client-IP",
		"X-Real-IP",
	}

	for _, h := range proxyHeaders {
		v := r.Header.Get(h)
		ip = net.ParseIP(v)
		if ip != nil {
			return ip, nil
		}
	}

	// If none of the above yielded any results, get the leftmost IP address
	// from the X-Forwarded-For header.
	s := r.Header.Get("X-Forwarded-For")
	ipStrs := strings.SplitN(s, ", ", 2)
	ip = net.ParseIP(ipStrs[0])
	if ip != nil {
		return ip, nil
	}

	// When everything else fails, just return the remote address as understood
	// by the stdlib.
	ipStr, err := netutil.SplitHost(r.RemoteAddr)
	if err != nil {
		return nil, fmt.Errorf("getting ip from client addr: %w", err)
	}

	return net.ParseIP(ipStr), nil
}

```

**Comment by thb007** [comment]
Here is a go project https://github.com/tomasen/realip

**Comment by liang-hiwin** [comment]
By capturing packets I found that when routedns is used as the upstream of any dns program, the edns ip disappears

**Comment by liang-hiwin** [comment]
@folbricht

![0YG_NVT21OMM5F_%PD4I9CA](https://user-images.githubusercontent.com/17548936/191987429-e9b6e80d-239f-43ca-9757-e776bbe941b7.png)

**Comment by folbricht** [comment]
While routedns can be configured to drop the subnet option, it shouldn't do that without specific config. I assume you don't have anything like that in your config file.

In your screenshots I can't quite see enough to say where the EDNS option is dropped. Would you be able to capture both ends? So capture the query that is sent to routedns, and the query it then forwards. I suspect it's not being sent in this case. Also if you could explain a bit more about this setup that'd help. Like what's building the initial query, and how it's routed from the client, etc

**Comment by liang-hiwin** [comment]
Currently my dns is laid out like this unbound(127.0.0.1:5353) <------ routede(127.0.0.1:5405),
The forwarding upstream of unbound is routede, by the following command:

dig +subnet=172.217.163.46 www.google.com @127.0.0.1 -p 5405
dig +subnet=172.217.163.46 www.google.com @127.0.0.1 -p 5353

In this solution, only unbound edns are normal, and routede edns have disappeared.

Only using routede (0.0.0.0:53) alone, it does not act as an upstream of any dns program, will not have a problem.

dig +subnet=172.217.163.46 www.google.com @0.0.0.0 -p 53

This scheme routede edns is normal

**Comment by liang-hiwin** [comment]
If you want to reproduce my problem you can do this:
The first step is to install adguard home (https://github.com/AdguardTeam/AdGuardHome)

The second step is to install routedns

The third step adguard home Upstream DNS servers fill in routedns ([listeners.local-udp] port)

**Comment by liang-hiwin** [comment]
Currently my dns is laid out like this unbound(127.0.0.1:5353) <------adguard home(127.0.0.1:5400),
The forwarding upstream of unbound is adguard home, through the following command:
**dig +subnet=172.217.163.46 www.google.com @127.0.0.1 -p 5400
dig +subnet=172.217.163.46 www.google.com @127.0.0.1 -p 5353**
This scheme edns is normal

**Comment by folbricht** [comment]
Is there a way to reproduce it without installing Adguard?

**Comment by folbricht** [comment]
Wanted to try it with unound->routedns, but I haven't been able to configure unbound to forward to a local resolver yet

**Comment by liang-hiwin** [comment]
> Is there a way to reproduce it without installing Adguard?


If you don't install programs like adguard home as a routedns forwarder, you can't reproduce the problem, only using routedns as their upstream will reproduce the bug

**Comment by liang-hiwin** [comment]
> Wanted to try it with unound->routedns, but I haven't been able to configure unbound to forward to a local resolver yet

For this unbound configuration you can use   ，Please remove the suffix .txt

[unbound.conf.txt](https://github.com/folbricht/routedns/files/9640884/unbound.conf.txt)

**Comment by folbricht** [comment]
Thank you, this config worked. So I set this up like this

`dig @127.0.0.1 -p 5353 google.com +subnet=172.217.163.46` -> unbound (5353) -> routedns (1153) -> cloudflare:53

The OPT record with EDNS0 is passed all the way through as you can see even from just looking at the header (OPT in all of them).

![image](https://user-images.githubusercontent.com/3505107/192147682-c64fb796-8e78-4a22-935f-c02b6d1fa068.png)

The routedns config I used is simply this:
```toml
[resolvers.cloudflare-udp]
address = "1.1.1.1:53"
protocol = "udp"

[listeners.local-udp]
address = "127.0.0.1:1153"
protocol = "udp"
resolver = "cloudflare-udp"
```

I'm not seeing any issues with this. Are you able to repro with that setup?

**Comment by liang-hiwin** [comment]
> Thank you, this config worked. So I set this up like this
> 
> `dig @127.0.0.1 -p 5353 google.com +subnet=172.217.163.46` -> unbound (5353) -> routedns (1153) -> cloudflare:53
> 
> The OPT record with EDNS0 is passed all the way through as you can see even from just looking at the header (OPT in all of them).
> 
> ![image](https://user-images.githubusercontent.com/3505107/192147682-c64fb796-8e78-4a22-935f-c02b6d1fa068.png)
> 
> The routedns config I used is simply this:
> 
> ```toml
> [resolvers.cloudflare-udp]
> address = "1.1.1.1:53"
> protocol = "udp"
> 
> [listeners.local-udp]
> address = "127.0.0.1:1153"
> protocol = "udp"
> resolver = "cloudflare-udp"
> ```
> 
> I'm not seeing any issues with this. Are you able to repro with that setup?

Now you can reverse the order and test.

**Comment by liang-hiwin** [comment]
dig @127.0.0.1 -p 5353 google.com +subnet=172.217.163.46 ->cloudflare:53->routedns (1153) ->unbound (5353)

**Comment by folbricht** [comment]
The first one is what I tested. The other 3 aren't valid.

2) this one goes through routedns only (port 1153) and we know that works

3) and 4) I don't know what these are meant to be. I can't route a query to cloudflare and then have it come back

**Comment by liang-hiwin** [comment]
> The first one is what I tested. The other 3 aren't valid.
> 
> 2. this one goes through routedns only (port 1153) and we know that works
> 3. and 4) I don't know what these are meant to be. I can't route a query to cloudflare and then have it come back

If you use this command to test:

**dig @127.0.0.1 -p 1153 google.com +subnet=172.217.163.46 -> unbound (5353) -> routedns (1153) -> cloudflare:53**

By capturing packets, it is found that routedns edns does not exist

**Comment by folbricht** [comment]
Still works. This will only go through routedns and then to cloudflare. edns0 is still there on the query to CF

![image](https://user-images.githubusercontent.com/3505107/192149010-04c7f20e-00bd-470f-bd69-d9d927a28a22.png)

**Comment by liang-hiwin** [comment]
3/4 case

```
#####Use unbound as the upstream of routedns
[resolvers.unbound-udp]
address = "127.0.0.1:5353"
protocol = "udp"

[listeners.local-udp]
address = "127.0.0.1:1153"
protocol = "udp"
resolver = "cloudflare-udp"

**####unbound configure**

```
server:
	verbosity: 1
	interface: 127.0.0.1@5353
  interface: ::0@5353
	username: "root"
	access-control: 0.0.0.0/0 allow
	access-control: ::1 allow
	do-ip4: yes
	do-ip6: yes
	do-udp: yes
	do-tcp: yes
   
  num-threads: 4
	msg-cache-slabs: 8
	rrset-cache-slabs: 8
	key-cache-slabs: 8
	infra-cache-slabs: 8
	
	log-servfail: yes
	aggressive-nsec: yes
	hide-trustanchor: yes
	hide-version: yes
	hide-identity: yes
	harden-glue: yes
	qname-minimisation: yes
	qname-minimisation-strict: no
	minimal-responses: yes
	rrset-roundrobin: yes
	so-reuseport: yes
	####Set to no to use local parsing
	do-not-query-localhost: no
	infra-cache-numhosts: 500000
	so-rcvbuf: 16m
	so-sndbuf: 16m
	neg-cache-size: 32m
	msg-cache-size: 50m
	msg-buffer-size: 65552
	key-cache-size: 64m
	neg-cache-size: 32m
	rrset-cache-size: 100m

	outgoing-range: 16384
	outgoing-port-permit: 32768
	num-queries-per-thread: 8192
	outgoing-num-tcp: 2048
	incoming-num-tcp: 4096
	jostle-timeout: 300

	cache-min-ttl: 5
	cache-max-ttl: 60
	infra-host-ttl: 120
	infra-cache-min-rtt: 1000
	cache-max-negative-ttl: 360
	val-bogus-ttl: 60
	serve-expired: yes
	prefetch: yes
	prefetch-key: yes
	max-udp-size: 4096
	edns-buffer-size: 1232
    edns-tcp-keepalive: yes
    edns-tcp-keepalive-timeout: 120000
  
  
    client-subnet-zone: "." 
	send-client-subnet: 0.0.0.0/0
	send-client-subnet: ::0/0
	max-client-subnet-ipv6: 56
	max-client-subnet-ipv4: 24
	client-subnet-always-forward: yes
	module-config: "subnetcache validator iterator"
	root-hints: "/usr/local/etc/unbound/trust/root.hints"
	#auto-trust-anchor-file: "/usr/local/etc/unbound/trust/root.key"
	tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"
	minimal-responses: yes
	unwanted-reply-threshold: 10000000

server:
forward-zone:
        name: "."
        forward-addr: 1.1.1.1@853  #cloudflare

```







```

**Comment by liang-hiwin** [comment]
Here is the relevant file for another test

**dig @127.0.0.1 -p 5405 ip.soshoulu.com +subnet=183.225.1.1**

[routedns.zip](https://github.com/folbricht/routedns/files/9641002/routedns.zip)

**Comment by folbricht** [comment]
Still working fine. The DoT config in your unbound.conf didn't work so I switched it to plain DNS. The edns0 record is present as it should be.

**Comment by liang-hiwin** [comment]
> Still working fine. The DoT config in your unbound.conf didn't work so I switched it to plain DNS. The edns0 record is present as it should be.

https://github.com/folbricht/routedns/issues/260#issuecomment-1257211101  

trouble you to test this

**Comment by folbricht** [comment]
Tried that too, edns0 still works, with or without unbound in front of it.

I think at this point it'd be best if you could try to find the issue by simplifying the routedns config if you believe it's dropping the edns0 somewhere. It's possible one of the groups, like the blocklist or cache is doing that. Once you find a simple config that shows the issue I'll take another look.

Also, when you test, restart both routedns and unbound beforehand to avoid using any caches.

**Comment by liang-hiwin** [comment]
> Tried that too, edns0 still works, with or without unbound in front of it.
> 
> I think at this point it'd be best if you could try to find the issue by simplifying the routedns config if you believe it's dropping the edns0 somewhere. It's possible one of the groups, like the blocklist or cache is doing that. Once you find a simple config that shows the issue I'll take another look.
> 
> Also, when you test, restart both routedns and unbound beforehand to avoid using any caches.

Sorry, I still have a problem here

**Comment by folbricht** [comment]
Ok, let's double-check we're using the same setup and looking at the same thing.

- Your client is `dig @127.0.0.1 -p 5405 google.com +subnet=183.225.1.1`
- It then hits unbound which forwards it to routedns
- routedns uses the config from your zip

And if you now capture the traffic after routedns, the edns0 option is not present in the query?

Can you capture a full pcap of every query along this chain? You should be able to do it like this `sudo tcpdump -i any -s 0 -w dns.pcap "port 53 or port 5404 or port 5405"` This may capture unrelated dns from the host so you can filter it down further with the upstream IP.

**Comment by liang-hiwin** [comment]
```
[bootstrap-resolver]
address = "223.5.5.5:53"
protocol = "udp"

[groups.random]
type   = "round-robin"
resolvers = ["alidns_1_resolver", "qq_1_resolver"]

[resolvers.alidns_1_resolver]
address = "https://223.5.5.5/dns-query"
protocol = "doh"
edns0-udp-size = 1232

[resolvers.qq_1_resolver]
address = "https://doh.360.cn:443/dns-query"
protocol = "doh"
edns0-udp-size = 1232

[listeners.local-udp]
address = "0.0.0.0:5405"
protocol = "udp"
resolver = "cloudflare-rrl"

[listeners.local-tcp]
address = "0.0.0.0:5405"
protocol = "tcp"
resolver = "cloudflare-rrl"

[groups.cloudflare-rrl]
type = "ecs-modifier"
resolvers = ["random_cached"]
ecs-op = "add" # "add", "delete", "privacy". Defaults to "" which does nothing.
ecs-address = ""
ecs-prefix4 = 24
ecs-prefix6 = 56

[groups.random_cached]
type = "cache"
resolvers = ["updated_ttl"]
cache-size = 1000000
cache-negative-ttl = 60
#cache-answer-shuffle = "random"
cache-flush-query = "zh.cache."

[groups.updated_ttl]
type = "ttl-modifier"
resolvers = ["random"]
ttl-min = 30
ttl-max = 60
```

[tcp.cap.zip](https://github.com/folbricht/routedns/files/9646268/tcp.cap.zip)

**Comment by liang-hiwin** [comment]
I have deleted a lot of the configuration and still have problems

**Comment by folbricht** [comment]
From your log, the issue is this? `error="unexpected status code 503" id=local-udp protocol=udp qname=google.com.hk.` and not actually missing edns0?

**Comment by liang-hiwin** [comment]
> From your log, the issue is this? `error="unexpected status code 503" id=local-udp protocol=udp qname=google.com.hk.` and not actually missing edns0?

I haven't opened the log log, and the packet capture edns also disappeared.

**Comment by folbricht** [comment]
I tried your config from above and without any modifications, I see this:
```
$ dig @127.0.0.1 -p 5405 qq.com +subnet=183.225.1.1

; <<>> DiG 9.16.31-RH <<>> @127.0.0.1 -p 5405 qq.com +subnet=183.225.1.1
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39678
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; MBZ: 0x0100, udp: 2048
; CLIENT-SUBNET: 127.0.0.0/24/0
;; QUESTION SECTION:
;qq.com.				IN	A

;; ANSWER SECTION:
qq.com.			60	IN	A	123.151.137.18
qq.com.			60	IN	A	203.205.254.157
qq.com.			60	IN	A	61.129.7.47
qq.com.			60	IN	A	183.3.226.35

;; Query time: 1388 msec
;; SERVER: 127.0.0.1#5405(127.0.0.1)
;; WHEN: Sat Oct 01 11:02:48 CEST 2022
;; MSG SIZE  rcvd: 134
```

routdns logs:
```
TRAC[0293] sending query                                 addr="223.5.5.5:53" qname=doh.360.cn.
DEBU[0294] modified response ttl                         client=127.0.0.1 id=updated_ttl qname=qq.com. qtype=A
```

Do you still see the issue? You wouldn't be able to see EDNS0 in pcap if the upstream traffic is encrypted.

**Comment by liang-hiwin** [comment]
> addr="223.5.5.5:53" qname=doh.360.cn.

Thank you for taking the time to answer this question. But at present this problem will lead to inaccurate parsing results

**Comment by cbuijs** [comment]
Maybe irrelevant now, but when you are using Unbound, do you have below lines in the Unbound config?
```
module-config: "subnetcache validator iterator" # Subnetcache Enables ECS
client-subnet-always-forward: yes               # use "no" if DNS Client already provide ECS
send-client-subnet: 0.0.0.0/0                   # Allow ECS for all IPv4 clients
send-client-subnet: 0::/0                       # Allow ECS for all IPv6 clients
```
The `subnetcache` bit actually activates adding the ECS to the query.

**Comment by liang-hiwin** [comment]
> Maybe irrelevant now, but when you are using Unbound, do you have below lines in the Unbound config?
> 
> ```
> module-config: "subnetcache validator iterator" # Subnetcache Enables ECS
> client-subnet-always-forward: yes               # use "no" if DNS Client already provide ECS
> send-client-subnet: 0.0.0.0/0                   # Allow ECS for all IPv4 clients
> send-client-subnet: 0::/0                       # Allow ECS for all IPv6 clients
> ```
> 
> The `subnetcache` bit actually activates adding the ECS to the query.

yes i added with
