### ISSUE TITLE
Adding "resolvers" to "routers" to chain/order resolution items

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#265]
For efficiency, steering and more have more granular/specific control, I suggest a `resolvers` chaining feature. It would look something like this using a `resolvers` (instead of `resolver`) in a routes rule using `routers`:
```
[routers.example-chain]
routes = [
    {name = '\.google\.com\.$", resolvers = ["filter-query", "filter-response", "doh-google"]},
    {resolver = "default-resolver"},
]
```
It will go in order of `resolvers` as defined, and only goes to the next one in the "chain" if the query/response is unmodified, if not, it reverts to the same operation as "resolver" and complete `routes` as before and go back up the "chain" with the result as is.
If the whole chain completes, it should work the same way as with (a single) "resolver" and go back up the "chain". with the result as is.

Use case example: if I have a chain of listeners/groups/resolvers, for particular reasons, I might need a same group for different purposes, now I need a couple to keep the "chain" of resolution going and provides duplication of config-code. Harder to maintain, and perhaps even more resource hungry.

**Comment by cbuijs** [comment]
Need my coffee... Already discussed this in #55, duh :-).

**Comment by liang-hiwin** [comment]
I haven't seen the project update recently, I'm so sad

**Comment by folbricht** [comment]
@liang-hiwin I just don't have a lot of time to work on it at the moment. It may get better this winter.

@cbuijs I don't fully understand how the list of resolvers on a route would be used. If the list is `resolvers = [A, B]`, when would it pick B over A for example?

**Comment by cbuijs** [comment]
@folbricht No. It will do it all in sequence. I think we discussed it before, and the "return" path is kind of not possible.

**Comment by cbuijs** [comment]
Forget it, makes things too complex.
