### ISSUE TITLE
Ability to block/handle classes other then "IN"

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#27]
Would it be possible to add the ability to add `class` to router rules, same way as `type`?
For now only the `IN` class is supported/defaulted, but no way to steer it.

Classes (besides `IN`) available can be found here:
https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-2

Not a huge pain or need, but seems an easy one to stick in ;-).

**Comment by folbricht** [comment]
That's on the issue-27 branch now, you can just add `class=ANY` to a route in the config. For now I'm using these terms "INET", "CSNET", "CHAOS", "HESIOD", "NONE", "ANY". Would the shorter ones like IN or HS be better? Which spelling is more common/standard?

**Comment by cbuijs** [comment]
The short syntax is very/more common and also used in lookup tools (like dig).

**Comment by cbuijs** [comment]
Getting this error when using it:

`Error: failure parsing routes for router 'class-filter' : unknown type 'INET'`

**Comment by cbuijs** [comment]
Looks like line 64 in router.go needs to be `stringToClass` instead of `stringToType` ?

**Comment by folbricht** [comment]
yes, sorry about that. Also changed the names to: "IN", "CH", "HS", "NONE", "ANY"

**Comment by cbuijs** [comment]
All working perfect now, thanks!

**Comment by folbricht** [comment]
Merged in https://github.com/folbricht/routedns/pull/29
