### ISSUE TITLE
Weird "rule" info at response-domain logging

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#276]
The `response-domain` when hit, logs what is hit, but I think there is a glitch in the `rule` part.

`msg="blocklist match, forwarding to blocklist-resolver" client=1.2.3.4 id=filter-response-domain qname=ogs.google.com. qtype=A resolver=noerror rule="&{BLOCK-CLOAK .www3.l.google.com}"`

The `rule="&{BLOCK-CLOAK .www3.l.google.com}"` part.

Looks like the `name` (BLOCK-CLOAK) is not accepted and concatenated wrongly.

**Comment by folbricht** [comment]
Good catch. Can you try https://github.com/folbricht/routedns/pull/277? It should be fixed there.

**Comment by cbuijs** [comment]
Did a quick run/glance, and looks okay. Will let it run for a while and report back.

**Comment by cbuijs** [comment]
Nope, still having the same issue:
```
msg="blocklist match, forwarding to blocklist-resolver" client=1.2.3.4 id=filter-response-domain-minimal qname=atconnect.npo.nl. qtype=A resolver=noerror rule="&{BLOCK-CLOAK .at-o.net}"
```
Coming from:
```
[groups.filter-response-domain-minimal]
type = "response-blocklist-name"
resolvers = ["filter-response-ip-minimal"]
blocklist-refresh = 14400
blocklist-resolver = "nxdomain"
blocklist-source = [
        {name = "BLOCK-CLOAK", format = "domain", source = "/opt/routedns/lists/block.cloak.list"},
]
```

**Comment by folbricht** [comment]
That is strange, I only see this log in one place that that's been updated to a string. Can you double-check you're on the `issue-276` branch and using a new build? Also, this is a name-based response blocklist, correct?

**Comment by cbuijs** [comment]
I did check, and even did a manual build to make sure (see below), and still same issue.

And yes, it is the name based responselist `type = "response-blocklist-name"`.

```
Your branch is up to date with 'origin/master'.
From https://github.com/folbricht/routedns
 * branch            issue-276  -> FETCH_HEAD
 = [up to date]      issue-276  -> origin/issue-276
Updating afebcd1..42aa7d7
Fast-forward
 response-blocklist-name.go | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by folbricht** [comment]
Hmm, `Your branch is up to date with 'origin/master'` suggests it's not the `issue-276` branch. But I think the change in the PR is good to go to master anyway.

**Comment by folbricht** [comment]
It's been merged to master

**Comment by cbuijs** [comment]
I am using the master/latest version (without patching it up, straight from the source), and still the same, and only for response-domain:
```
msg="blocklist match, forwarding to blocklist-resolver" client="1.2.3.4" id=filter-response-domain qname=media.evo.co.uk. qtype=A resolver=noerror rule="&{TRACKER-AT .cedexis.net}"
```

**Comment by folbricht** [comment]
Can you build off the `issue-276-debug` branch and try again? This should add a new field to that log line `issue-276-debug=...` to help narrow this down. But really there's only two places in the code where this is emitted, and one of those is in the ip response blocklist.

You can also double-check that in response-blocklist-name.go in line 92 you see `.WithField("rule", rule.Rule)` instead of the old `.WithField("rule", rule)`

**Comment by cbuijs** [comment]
Looks like this using issue-276-branch:
```
msg="blocklist match, forwarding to blocklist-resolver" client="1.2.3.4" id=filter-response-domain issue-276-debug="string-\".trafficmanager.net\"" qname=arc.msn.com. qtype=A resolver=noerror rule=.trafficmanager.net
msg="blocklist match, forwarding to blocklist-resolver" client="1.2.3.4" id=filter-response-domain issue-276-debug="string-\".bac.com\"" qname=www.bankofamerica.com. qtype=A resolver=noerror rule=.bac.com
```

When reverting to master:
```
msg="blocklist match, forwarding to blocklist-resolver" client="1.2.3.4" id=filter-response-domain qname=www.bankofamerica.com. qtype=AAAA resolver=noerror rule="&{TRACKER-AT .bac.com}"
msg="blocklist match, forwarding to blocklist-resolver" client="1.2.3.4" id=filter-response-domain qname=www.bankofamerica.com. qtype=A resolver=noerror rule="&{TRACKER-AT .bac.com}"
```

**Comment by folbricht** [comment]
It looks like your master branch isn't advancing for some reason. Can you run `git checkout master && git pull && git show`? It should show this
```
commit 818d7b73e52b6d375afae39b12a3cf17cb4ab047 (HEAD -> master, origin/master, origin/HEAD)
Author: github-actions <github-actions@github.com>
Date:   Fri Feb 3 00:24:18 2023 +0000
```

**Comment by cbuijs** [comment]
This is what I get when building from "master" (and the logging issue persist):

```
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
commit 818d7b73e52b6d375afae39b12a3cf17cb4ab047 (HEAD -> master, origin/master, origin/HEAD)
Author: github-actions <github-actions@github.com>
Date:   Fri Feb 3 00:24:18 2023 +0000

    Automatic Version bump from GitHub Action at: Fri Feb  3 00:24:18 UTC 2023 v0.1.21

diff --git a/version.go b/version.go
index 38400d9..262655c 100644
--- a/version.go
+++ b/version.go
@@ -1,8 +1,8 @@
 package rdns
 
 var (
-       BuildVersion string = "v0.1.20"
-       BuildTime    string = "Thu Jan 26 19:26:50 UTC 2023"
+       BuildVersion string = "v0.1.21"
+       BuildTime    string = "Fri Feb  3 00:24:18 UTC 2023"
        BuildNumber     string = "4"
 )
```

**Comment by folbricht** [comment]
That's correct, it should work now. The output from the `issue-276-branch` branch was correct, and I didn't change anything compared to master apart from adding a field to the log. If you build it now it should show `rule=.bac.com` etc

**Comment by cbuijs** [comment]
All seems to work correct now!
