### ISSUE TITLE
[Feature Request] Redis DNS cache

### ISSUE THREAD

**Issue by alpominth** [folbricht/routedns#278]
A Redis backed DNS cache would be very good to have implemented in routedns.

The cache would be persistent and would persists across reboots.

These projects have this feature already implemented:

[Unbound](https://github.com/NLnetLabs/unbound)
[Blocky](https://github.com/0xERR0R/blocky)
[Overture](https://github.com/shawn1m/overture)
[mosdns-cn](https://github.com/IrineSistiana/mosdns-cn)
[GODNS](https://github.com/kenshinx/godns)
[redins](https://github.com/arvancloud/redins)

This package could serve as a basis for this implementation: https://github.com/go-redis/redis

**Comment by alpominth** [comment]
@folbricht

Do you consider my suggestion? I found RouteDNS the most advanced DNS forwarder written in Go, and this idea to implement caching of DNS queries with Redis is overkill to me. I don't think it's difficult to implement, you could just follow the steps in another project here: https://github.com/shawn1m/overture/commit/5f9e7b12b8239f18defd8caec35e09e8f2fa3139

(I am not a GO programmer, if I were an I would have already implemented this idea even if it was only for personal usage only).

**Comment by folbricht** [comment]
It can certainly be implemented, probably not too difficult. I'm a bit short on time but can take a quick look at it.

**Comment by alpominth** [comment]
Thanks, no pressure, no problems, I have been using Unbound for persistent caching with Redis but it requires bothering modifications on Redis.

Changing the subject, a very nice and useful feature would be prefetching, it's already implemented on separate branches, if you could merge into the master would be a good idea: https://github.com/folbricht/routedns/compare/master...prefetch-feature-2

**Comment by folbricht** [comment]
Weird, prefetch was supposed to be merged already, just re-opened a PR https://github.com/folbricht/routedns/pull/279, missing docs still

**Comment by alpominth** [comment]
Very good, but I noticed that two important options of branch https://github.com/folbricht/routedns/compare/master...prefetch-feature-2 are missing:

cache-ttl-polling-check-interval = 60
record-query-hits-min = 1

==> https://github.com/folbricht/routedns/commit/15df284fe9224e9170b38300f60f225f12a6ada0#diff-69854e85865fdfa4a40d619bcfe214fedcba863aadf7c1a55062ab7f827991f6R19

It would be very good for who visits sites periodically and want to keep the cache up to date. Together with Redis cache would be overkill.

**Comment by folbricht** [comment]
https://github.com/folbricht/routedns/pull/280 is the first step to implementing a redis backend for the cache.

**Comment by alpominth** [comment]
@folbricht

Thanks for considering my suggestion.

The reason why **cache-ttl-polling-check-interval** and **record-query-hits-min** of branch https://github.com/folbricht/routedns/compare/master...prefetch-feature-2 would be a good idea is the fact that often queried domains could be prefetched and updated without having to update the entire cache when the TTLs of all cached items has fallen bellow a limit. `cache-prefetch-trigger` is good, but with a very large cache could make many DNS requests to keep the entire cache updated. With **cache-ttl-polling-check-interval** and **record-query-hits-min** in a very large cache can make only the most visited domains to be updated.

This is my another suggestion, [it is already implemented in Blocky](it is already implemented in Blocky), but Blocky has a problem in the caching of requests that prevents authority and OPT pseudosection to be stored in cache.

**Comment by folbricht** [comment]
https://github.com/folbricht/routedns/pull/315 has an (incomplete) draft implementation of this. It doesn't read anything from the cache yet, but stores records in it and can be used to test the configuration.

Feel free to take it for a spin. You can see it storing records by looking into redis yourself. It doesn't currently support any key-prefixes. Not sure if we need that to allow sharing a Redis that is used for other things too perhaps. It should also work over unix sockets, though I haven't tested that yet.

**Comment by folbricht** [comment]
Just added support for reading from redis. Caching seems to be working for me so far. Still no support for key prefixes

**Comment by alpominth** [comment]
Very good.

I will test here.
