### ISSUE TITLE
Sometimes getting a segmentation violation refreshing blocklist

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#291]
Not always, but sometimes (no clue what triggers it), when blocklists are renewed/refreshed (not initianal load), I get a segmentation error which crashes RouteDNS, below an example/output.

Happens roughly twice or three times a week. Seems to be random, and after restarting it then runs for days without any issues.

```
Mar 20 03:45:55 dns ROUTEDNS: msg="writing rules to cache-dir" url="https://raw.githubusercontent.com/cbuijs/accomplist/master/homograph/routedns.blocklist.top-n.domain.list"
Mar 20 03:45:55 dns ROUTEDNS: error: invalid memory address or nil pointer dereference
Mar 20 03:45:55 dns ROUTEDNS: segmentation violation code=0x1 addr=0x20 pc=0x93b409]
Mar 20 03:45:55 dns ROUTEDNS: 
Mar 20 03:45:55 dns ROUTEDNS: [running]:
Mar 20 03:45:55 dns ROUTEDNS: 0x13?}})
Mar 20 03:45:55 dns ROUTEDNS: #011/tmp/routedns-build/blocklistdb-multi.go:24 +0x89
Mar 20 03:45:55 dns ROUTEDNS: github.com/folbricht/routedns.(*Blocklist).refreshLoopBlocklist(0xc000395a70, 0x0?)
Mar 20 03:45:55 dns ROUTEDNS: #011/tmp/routedns-build/blocklist.go:179 +0xd1
Mar 20 03:45:55 dns ROUTEDNS: github.com/folbricht/routedns.NewBlocklist
Mar 20 03:45:55 dns ROUTEDNS: #011/tmp/routedns-build/blocklist.go:72 +0x185
```

**Comment by charlieporth1** [comment]
@cbuijs I think its a loop

 https://github.com/folbricht/routedns/blob/e9bb881f561f753a998d938e03436eac024336d5/blocklistdb-multi.go#L24 is inside itself

**Comment by folbricht** [comment]
I think https://github.com/folbricht/routedns/pull/259 will have to come out. It wasn't quite ready and there's a few other issues with it like it starts up and loads the blocklists later. I'll have to revisit that

**Comment by folbricht** [comment]
I think https://github.com/folbricht/routedns/pull/294 may fix this as well

**Comment by cbuijs** [comment]
Build master with `issue-286` and `issue-153-3`, and so far looking good.

**Comment by cbuijs** [comment]
Oops.... Found something.

When you clear the `cache-dir` directory (to force downloading everything again), and restart RouteDNS, it will download all the lists (that works, `cache-dir` gets updated correctly), and then stalls after the last one and just hangs (no errors/messages). Restarting it again and everything will run fine.

**Comment by folbricht** [comment]
Can you list the exact steps? I can't reproduce this. It sounds like it hangs if routedns starts up with an empty cache-dir but that seems to work fine for me. Tried with 3 lists in the config

**Comment by cbuijs** [comment]
I tried to record it and now it just works fine. Might be just a CPU or Swap overload so it just went slow or something.

Steps:
- With a running RouteDNS, clear the cache-dir.
- Restart RouteDNS
- Previous it would hang after the last list was downloaded
- Restart RouteDNS
- Now it Runs fine

No errors, the process still runs actually but very low activity. I didn't check other process, CPU, Memory at the time, but will when it happens again. As said, it went away and might be nothing to do with RouteDNS.

Cheers,
-Chris.

**Comment by cbuijs** [comment]
Seems to be fixed.
