### ISSUE TITLE
Integrate with Google Safe Browsing

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#297]
Just an idea....

Google Safe Browsing (API driven) can be used to validate domains if they are malicious or not. Would be cool to have this validation and return responses based on it (caching becomes important of course, just to keep delays in responses low).

When safe, nothing will be touched. When malicious/not-safe, a resolver can be picked to provide a response.

See here:
https://github.com/google/safebrowsing.git

Keeping a disk-cache on responses already gathered that gets (re)loaded at startup makes sense to keep number of API-Calls and duplicates low. Either make the existing cache group persistent this way, or make it part of the feature.

**Note:** Maybe a generic approach where other "reputation" based services (API based) can be used as well. Like AlienVault, OpenDNS, DomainTools, Spamhaus, etc...

**Comment by folbricht** [comment]
Seems pretty straightforward to implement. Though that project specifically seems to require an apikey, and doesn't appear to have been active for several years.

**Comment by cbuijs** [comment]
I am not to invested with it, but it is havealy used by browsers and some DNS providers (like NextDNS). There are other libraries. The API key sucks a little bit, but it seems quite easy to document how to get one and configure it I guess. I think any service with an API will require it anyway.
