### ISSUE TITLE
Make "cache" persistent

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#299]
It would be cool, especially on larger environments, to be able to make `cache` persistent between reloads of RouteDNS and don't lose it. This to avoid a huge uptick or burst in load on environments with high number of queries when reloading/restarting.

A common way doing so is to flush the cache every X amount of time to disk/file, and this file is loaded when RouteDNS (re)starts. TTLs stay ticking, so on startup the purge of the cache(file) needs to happen, based on the records original time-stamp and TTL left, to avoid stale/old records to be served.

Config example (last 3 lines):
```
[groups.persitent-cache]
type = "cache"
resolvers = ["google-doh"]
cache-size = 8192
cache-negative-ttl = 60 # Seconds
gc-period = 30 # Seconds
cache-harden-below-nxdomain = true
cache-flush-query = "flush.cache."
cache-prefetch-trigger = 10 # Seconds
cache-prefetch-eligible = 30 # Seconds
persistent = true
persistent-save-period = 300 # Every 5 minutes
cache-file = "/opt/routedns/persistent.cache"
```

**Note:** Maybe even an option to "preload" the cache with our own records. This would enable generated/synthesized/spoofed answers for redirection, blocking, etc...

**Comment by cbuijs** [comment]
I agree. Not really care how it is done, the more flexibility the better :-). For me is not loosing cache between reloads is the heavy requirement. Sharing/Merging the cache among different instances of RouteDNS using Redis for example is quite cool too. It again reduces overhead and duplication.

**Comment by folbricht** [comment]
There's now a draft implementation of persistence on the `issue-229` branch. You can configure it like so
```toml
[groups.cloudflare-cached]
type = "cache"
resolvers = ["cloudflare-dot"]
backend = {type = "memory", filename = "/var/tmp/cache.json"}
```
It'll read from the file on startup and overwrite it on shutdown. The old configs should be supported (could you confirm?) Let me know how that works.

**Comment by cbuijs** [comment]
Will try coming days when I find some time. Does it keep track of TTL on their original timestamp?

Example, if a record is cached with TTL of 60 seconds and the cache get reloaded more than 60 seconds later it is gone, right?

**Comment by folbricht** [comment]
It's an exact dump of the state of the cache, so items can definitely "age" while routedns is shut down. These will be loaded again on startup, but get dropped shortly after.

**Comment by cbuijs** [comment]
Seems to work as expected.

Two things so far:

- Does the dump contains the EDNS info? So it still matches which answers belong to which subnet? I see some intermediate results after reload (nothing crazy, need more time to pinpoint).
- Can we use SIGUSR1 to force/reload the cache?
- Can we use SIGUSR2 to force/write the cache?

For the last, could run a cronj-ob every 15 mins or so to dump the cache out, in case of a crash or something, it is not to old?

Also dumping the cache just to see what's in it (without bringing down RouteDNS) and see the "state" of the cache helps in some troubleshooting scenarios I think.

**Comment by folbricht** [comment]
Writing periodically is quite simple to implement, but reading from it seems slightly wrong (outside of testing). Since it would potentially load older data from disk while it's active. Not sure what the use-case would be for reading.

As for triggering a write, I'd prefer to configuring a write-interval instead of using signals. Ideally something that works on non-Linux as well.

**Comment by cbuijs** [comment]
Forcing a read would be cool to load/read a cache for the same reasons Alpominth said, To share cache among multiple instances of RouteDNS. Redis might be a better option and actively sync or something. In that case "merging" would be a better option (as option to say read cache from file and merge/overwrite the one in memory). Same for writing, merge with the existing file (and prune stale/expired ones).

**Comment by folbricht** [comment]
Having two instances accessing the same file like that is just going to cause issues since we'd need a locking mechanism to avoid them stepping on each other. Redis (and perhaps other database backends) is the safer option.

**Comment by folbricht** [comment]
There's now an optional `save-interval` that can be set on the memory backend which will write the cache content to disk while the process is running.
```toml
backend = {type = "memory", size = 1000, filename = "/tmp/cache.json", save-interval = 60}
```

**Comment by cbuijs** [comment]
Works as expected.

**Comment by alpominth** [comment]
I have been using persistent cache for 3 months in a dozen and a half of Windows 10 PCs, no problem until now: https://github.com/folbricht/routedns/pull/300#issuecomment-1532240509
