### ISSUE TITLE
Ability for dealing with NXDOMAIN responses in the cache.

### ISSUE THREAD

**Issue by alpominth** [folbricht/routedns#301]
By default, RouteDNS treats NXDOMAIN responses as positive answers as they have a SOA.

Let's suppose I have configured RouteDNS for storing queries in the cache for 10 days, I use to browse a site, this site has its registration expired and its saved entry in the cache expires too nearly the same time. If I enter again in this expired domain I will get a NXDOMAIN response, but what if the site comes back after the NXDOMAIN response is written in the cache? I would have to blindly wait almost 10 days for noticing that the site came back.

That's why I think NXDOMAIN should be dealt apart from normal answers.

As https://github.com/folbricht/routedns/pull/300 is being developed, it would make possible to use RouteDNS for persistent/permanent caching, and storing a NXDOMAIN for weeks as well as normal answer is not a very good idea, as a non-existent domain can be a previously watched domain that gone down for some hours/days, if RouteDNS accidentally stores its temporary NXDOMAIN response, the site would be available to the user only after a long time.

Resuming my suggestion: A domain can be temporarily a non-existent domain, and if RouteDNS would store its dead state and the site comes back soon, one would possible need to wait a long time for noticing the site came back.

Thanks.

**Comment by cbuijs** [comment]
You can already work around this by using `cache-negative-ttl` as cache option (see  docs). You can set how long a "negative" answer, meaning anything not being `NOERROR` gets cached regardless of any TTL.

I think the default is 60 seconds anyway. @folbricht might be able to answer this.

Also "persistent" cache is not to cache "forever" but keep the cache and don't lose it during reloads. The TTLs are still honored over time.

**Comment by folbricht** [comment]
I could certainly add a flag to set the max TTL of NXDOMAIN responses, but how do other caches handle this situation? I suppose most would trust the SOA.

**Comment by cbuijs** [comment]
It differs. Mostly take SOA TTL if exist, but SOA doesn't always exist. Some don't cache at all, some a minimal like 60 seconds. I think your implementation is common. Mayb an extra flag to ignore-soa on negative ttl.

**Comment by cbuijs** [comment]
@alpominth 

> I took a look in the config doc and I couldn't see any option to control NXDOMAIN responses.

It is called `cache-negative-ttl`.

**Comment by cbuijs** [comment]
Yeah, I am testing, and indeed, even when stripping out the authoritative section with `minimize`, the TTL's are not set/changed. The SOA is always there. This is changed behaviour for sure. Before it was working (as I needed it).

Ping @folbricht: 

- Looks like "minimize" is not stripping the `authoritative`, only when RCODE is a `NOERROR`. I think it is safe to do it for any RCODE, just keep the `answer` section intact.
- As discussed, the `cache-negative-ttl` option, needs another option to force/overwrite the TTL of any negative answer regardless if there is a `SOA` or not.

**Comment by folbricht** [comment]
https://github.com/folbricht/routedns/pull/303 should take care of the response-minimizer.

**Comment by folbricht** [comment]
And https://github.com/folbricht/routedns/pull/304 introduces a new option to the cache which can be used to set upper boundaries on the time something can be cached, based on the status code. Instead of handling NXDOMAIN explicitly, this is much more flexible as it can be set for other RCODES too, in fact it can be defined for more than one code.

I've only done minimal testing. That branch is based on master so it won't have the cache-persistence features.

**Comment by cbuijs** [comment]
Same here, works as expected. Great job!
