### ISSUE TITLE
branch-issue-229

### ISSUE THREAD

**Issue by charlieporth1** [folbricht/routedns#308]
This is running in a docker instance of routedns as a anycast loadbalancer to another routedns instance 
```
Application error 0x0 (remote)" id=local-udp protocol=udp qname=youtubei.googleapis.com.
time="2023-05-04T12:25:13Z" level=error msg="failed to resolve" addr=":53" client=17172.58.80.76 2.58.80.76 error="Application error 0x0 (remote)" id=local-udp protocol=udp qname=vpn.ctptech.dev.
time="2023-05-04T12:25:14Z" level=error msg="failed to resolve" addr=":53" client=172.58.137.54 error="Application error 0x0 (remote)" id=local-udp protocol=udp qname=edge-007.usmes1.icloud-content.com.
```

**Comment by charlieporth1** [comment]
Issue is no longer happening

**Comment by folbricht** [comment]
I suspect the issue still exists. It's likely very rare and not related to any recent changes. Once I have a bit more time I'll try to spot the root cause. Must be a race condition in the the way queries are pipelined onto a resolver. I'd expect it to sometimes show under load.
