### ISSUE TITLE
[Question] How to extract the client certificate to use with "client-crt" option?

### ISSUE THREAD

**Issue by alpominth** [folbricht/routedns#316]
When I try to load the .crt file from file I get the following error:
```
# /opt/routedns/routedns /opt/routedns/data/permcache/permcache.toml 
Error: failed to load client certificate from ./cf.crt
```

I tried the following commands:

`echo | openssl s_client -servername cloudflare-dns.com -connect cloudflare-dns.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > ./cf.crt`

`curl https://cloudflare-dns.com/dns-query -w "%{certs}" -o /dev/null > ./cf.crt`

When I extract the key from the certificate the option client-key works, I use this command:

`openssl x509 -noout -pubkey -in ./cf.crt -out ./cf.key`

**Comment by alpominth** [comment]
I found the command that should be used for that:

openssl x509 -in ./crt.pem -text -noout > ./crt

Closing this, but this topic can be a reference for ones which are searching for this question.

**Comment by folbricht** [comment]
You don't really need to strip the extra output you get from `openssl s_client`, that could be used as-is. But I'm confused about what you'd want to use the cert for. This could be used a CA perhaps, but not a client certificate since it's missing the key, and cloudflare-dns.com would trust it anyway (or even require a client cert).

**Comment by alpominth** [comment]
I want to use to prevent MITM attacks?

I got new errors here.

How is the right way to extract the .crt file from a DoH server?

**Comment by folbricht** [comment]
MITM are kind of prevented already by you using TLS at all. routedns will check the name in the cert. If you want to limit what certs are trusted you can pin the cert presented by the server.

```

**Comment by alpominth** [comment]
I Got. Thank you.
