### ISSUE TITLE
Bootstrap resolver doesn't obbey the timeout set with query-timeout when the resolver is a plain resolver with hostname

### ISSUE THREAD

**Issue by alpominth** [folbricht/routedns#318]
This is easy to reproduce:

Bootstrap address is blocked by iptables for testing: `sudo iptables -A OUTPUT -p tcp -d 208.67.222.222 --dport 443 -j DROP`

==============

Config 1:

```
[bootstrap-resolver]
address = "208.67.222.222:443"
protocol = "tcp"

[resolvers.manual]
address = "https://dns.nextdns.io/dns-query"
protocol = "doh"
query-timeout = 10

[listeners.local-udp-ipv4]
address = "127.0.0.1:1053"
protocol = "udp"
resolver = "manual"
```

Result:

```
$ time host -p 1053 g.co 127.0.0.1
;; communications error to 127.0.0.1#1053: timed out
;; communications error to 127.0.0.1#1053: timed out
;; no servers could be reached

real	0m10.029s
user	0m0.005s
sys	0m0.005s
```

/\ Query timeout is obeyed.

===============

```
[bootstrap-resolver]
address = "208.67.222.222:443"
protocol = "tcp"

[resolvers.manual]
address = "one.one.one.one:53"
protocol = "tcp"
query-timeout = 10

[listeners.local-udp-ipv4]
address = "127.0.0.1:1053"
protocol = "udp"
resolver = "manual"
```

Result:

```
$ time host -p 1053 g.co 127.0.0.1
Using domain server:
Name: 127.0.0.1
Address: 127.0.0.1#1053
Aliases: 

Host g.co not found: 2(SERVFAIL)

real	0m2.022s
user	0m0.008s
sys	0m0.004s
```

/\ Query timeout is ignored.

**Comment by folbricht** [comment]
Thank you. Can you try the `issue-318` branch, and also add a timeout to the bootstrap resolver like so?

```toml
[bootstrap-resolver]
address = "208.67.222.222:443"
protocol = "tcp"
query-timeout = 10
```

**Comment by alpominth** [comment]
Yep, it's ready: https://github.com/folbricht/routedns/pull/319#issuecomment-1646897048

**Comment by alpominth** [comment]
**one.one.one.one:53** maps top Cloudflare default resolvers:

$ host one.one.one.one
one.one.one.one has address 1.0.0.1
one.one.one.one has address 1.1.1.1
one.one.one.one has IPv6 address 2606:4700:4700::1111
one.one.one.one has IPv6 address 2606:4700:4700::1001
