### ISSUE TITLE
Expand CIDR filtering with GEO/Region info?

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#32]
See subject, instead of having a CIDR, use a GEO-Code to block responses based on a GEO-Database (I myself use the free GeoLite2 one from Maxmind).

I suggest an config-option to point to the GEO-DB (if it is Maxmind, it would be `/usr/share/GeoIP/GeoLite2-City.mmdb`). This would give the ability to allow/block based on GEO-Name/Code. An IP in a response would be checked against the DB and it will give bag the tags/indentifiers to work with.

There are three 'tags' to identify:
```
CONTINENT (Like 'EUROPE')
COUNTRY (Like 'NETHERLANDS')
AREA (Like 'NORTH HOLLAND')
CITY (Like 'AMSTERDAM')
```
I would suggest the GEO-Based Name/Code to start with an add-sign (`@`), combinations of tags (in an `AND` capactity to match), would be possible to sepperate with a comma, example:
```
192.168.0.0/24
214.123.0.22/32
@COUNTRY:CHINA
@COUNTRY:NETHERLAND,CITY:AMSTERDAM
```
Maybe include the ability to use "ID" from the DB, I never looked into it, but could be a quicker way to do thing.

Note: Their could be spaces in the names.

Maxmind database documentation (There is the free MMDB database andthere are existing GEOLite GO lib/modules on github):
https://dev.maxmind.com/geoip/geoip2/geolite2/

**Not high prio**, just a really nice feature to geo-fence connectivity.

P.S. Maybe also nice for expanding the listeners allow/acl feature.

**Comment by cbuijs** [comment]
Maybe it is easier to make a separate response-blocklist type/group actually as you can route or chain things anyway for maximum flexibility.

**Comment by folbricht** [comment]
In this particular case it's actually easier to add a new blocklist format to the existing blocklist that performs blocking by CIDR currently. Since both check the IPs, it seems to make sense, just with a different rule-set.

As for the rules, using the GeoName IDs looks to be the simpler solution as that avoids all the string comparisons in multiple languages. And doing that would also make it unnecessary to specify more than one location per rule, since they're unique, so no need to provide COUNTRY + CITY. Again, just having one value to compare makes it a lot faster and simpler. It'd have to be prefixed like so:
```
@COUNTRY:3017382
@CITY:2759794
```

**Comment by cbuijs** [comment]
What about combos, like this city and country need to match. As there are many cities that also have the same name as countries (or states/provinces).

Also documentation on what is what and where to find the numbers needed might need a reference, the maxmind documentation is a bit of a handful to go through and find stuff.

**Comment by folbricht** [comment]
The IDs seem to be somewhat standard, and you can look them up here for example: http://www.geonames.org/ That avoids a lot of the ambiguity since there's only one ID per entity.

**Comment by folbricht** [comment]
A first implementation now lives on the issue-32 branch. Seems to work, though I didn't do extensive testing with it yet. Please note that `response-blocklist-cidr` has been renamed to `response-blocklist-ip`, but the old name still works.

```toml
[groups.cloudflare-blocklist]
type                = "response-blocklist-ip"
resolvers           = ["cloudflare-dot"]
blocklist-format    = "location"
blocklist           = [
  "continent:6255148", # Europe
  "country:2017370",   # Russia
  "city:7839805",      # Melbourne
]
```

Like with the other blocklists, you can define a list of remote or local sources with refresh etc. Should work just the same. One thing that may not work is updating the geoip DB on disk without restarting. Not tried it, but wouldn't be surprised if it failed after an external program writes to the file. A list refresh by routedns would then fix it again.

**Comment by cbuijs** [comment]
Just for info: `location-db` is used to point to the MaxMind MMDB.

**Comment by cbuijs** [comment]
Also for looking up the geonames-id, you can use this site:
https://www.geonames.org/

**Comment by cbuijs** [comment]
Everything seems to work fine, I did some tests with cities, countries and continents and all works as expected. Love that filtering (taking out the offending IP) still works so CDN's still work.

**Comment by folbricht** [comment]
Thanks for checking it out. Next steps are:
- Support comments at the end of the line in rules files
- Try out remote/local rules files
- Find out if GeoName IDs are completely unique and don't overlap between different categories. If so we could drop the prefix like `country:` and just list the IDs in rules which would simplify and speed things up a bit
- Improve logging of matches

**Comment by folbricht** [comment]
Pushed an update that allows same-line comments (with #) and logs the matching IP. Also tried out a local blocklist file which seems to work fine.
Couldn't find a definite statement that the GeoName IDs don't overlap, but it's likely they really are unique. With the ability to properly comment the lines now, the prefix is less useful. But even if I change it to just the ID, it'll still only check continent, country and city and ignore any other type of location. Perhaps that's a reason to keep the prefix to make it explicit?

**Comment by cbuijs** [comment]
Check this dump from Geonames:
https://download.geonames.org/export/dump/allCountries.zip

It actually contains **AL**L ids, and no overlap as far as I can see. You might check field number 9, as it tells if it is a continent (`^CONT$`), a country (`^PCL.*$`) or a city (`^PPL.*$`). Among those three all is unique. MaxMind uses the GeoNames coding of IDs, so should be fine.

**Comment by cbuijs** [comment]
I was already using the file based source, as it shared the code with the original cidr version :-). It works fine. Thanks for the ability to comment in files!

**Comment by folbricht** [comment]
Updated to just require the GeoNames ID now. This is much simpler.

```toml
[groups.cloudflare-blocklist]
type                = "response-blocklist-ip"
resolvers           = ["cloudflare-dot"]
blocklist-format    = "location"
blocklist           = [
  "6255148", # Europe
  "2017370", # Russia
  "7839805", # Melbourne
]
```

**Comment by cbuijs** [comment]
Works as expected.

**Comment by cbuijs** [comment]
### Reminder:
There is another part that can be used, and it is called `subdivisions` (basically States/Provinces/etc). It has a geoname-id as well.

See here list of Geonames-IDs:
https://github.com/cbuijs/my-routedns-config/blob/master/geonames/geonames-subdivision-ids.list

**Comment by folbricht** [comment]
The latest commit adds support for subdivision as well

**Comment by folbricht** [comment]
Merged to master in https://github.com/folbricht/routedns/pull/40, let me know if you find any issues with it
