### ISSUE TITLE
Question: How long keepalive persists in resolvers over TCP?

### ISSUE THREAD

**Issue by alpominth** [folbricht/routedns#324]
I'm testing the [Cloudflare hidden resolver](https://blog.cloudflare.com/welcome-hidden-resolver/), it's really slow on first connection with RouteDNS + Tor Socks5, but the subsequent connections are faster:

```
$ dig @127.0.0.1 -p 1053 t.co
;; communications error to 127.0.0.1#1053: timed out

; <<>> DiG 9.18.16-1-Debian <<>> @127.0.0.1 -p 1053 t.co
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29801
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: b9b69a813da3e6d6 (echoed)
;; QUESTION SECTION:
;t.co.				IN	A

;; ANSWER SECTION:
t.co.			30	IN	A	104.244.42.5
t.co.			30	IN	A	104.244.42.133
t.co.			30	IN	A	104.244.42.69
t.co.			30	IN	A	104.244.42.197

;; Query time: 1047 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1) (UDP)
;; WHEN: Tue Aug 22 22:54:40 EDT 2023
;; MSG SIZE  rcvd: 125

$ dig @127.0.0.1 -p 1053 t.co

; <<>> DiG 9.18.16-1-Debian <<>> @127.0.0.1 -p 1053 t.co
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37686
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: e1cdb47878989b83 (echoed)
;; QUESTION SECTION:
;t.co.				IN	A

;; ANSWER SECTION:
t.co.			28	IN	A	104.244.42.5
t.co.			28	IN	A	104.244.42.133
t.co.			28	IN	A	104.244.42.69
t.co.			28	IN	A	104.244.42.197

;; Query time: 669 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1) (UDP)
;; WHEN: Tue Aug 22 22:54:42 EDT 2023
;; MSG SIZE  rcvd: 125
```

Obviously, the subsequent is faster due to keepalive in TCP.

My question is: How long a keepalive persists with a TCP/DoH/DoT resolver in RouteDNS?

**Comment by folbricht** [comment]
It's less of an issue of keepalive I think, and more of how long connections are idle. TCP and DoT connections will be closed after they're idle for this long https://github.com/folbricht/routedns/blob/master/pipeline.go#L17 (unfortunately it's hard-coded at the moment). In most cases, the server actually closes idle tcp connections earlier than that anyway, I remember seeing one of the big resolvers shutting it down after 8s of not receiving a query through the connection.

For DoH, it'd be the default behavior of the HTTP client which manages a pool of connections.

**Comment by alpominth** [comment]
Ok, thanks.

I thought that RouteDNS kept the connections alive forever.
