### ISSUE TITLE
Support DoH over QUIC

### ISSUE THREAD

**Issue by folbricht** [folbricht/routedns#33]

**Comment by folbricht** [comment]
A client implementation now exists on the issue-33 branch. While it's pretty fast on subsequent queries, the initial query is rather slow, 200-300ms. Not yet sure why.

**Comment by folbricht** [comment]
https://github.com/folbricht/routedns/pull/34 adds support for both, listeners and resolvers

**Comment by cbuijs** [comment]
Checked with cloudflare-dns, and get this error:

`level=error msg="failed to open session" endpoint="cloudflare-dns.com:443" error="No compatible QUIC version found. We support [TLS dev version (WIP)], server offered [0xff00001b]" protocol=doq`

I guess they either do not do/support DNS, or TLS versions/crypts versions mismatch/unsupported?

Config used:
```
[resolvers.quic]
protocol = "doq"
address = "cloudflare-dns.com:443"
```

**Comment by cbuijs** [comment]
When using dns.google.com, some more info:

`level=error msg="failed to open session" endpoint="dns.google.com:443" error="No compatible QUIC version found. We support [TLS dev version (WIP)], server offered [0xca5a8a8a 0xff00001b 0xff000019 0x54303530 0x51303530 gQUIC 49 gQUIC 48 gQUIC 46 gQUIC 43]" protocol=doq
`

**Comment by cbuijs** [comment]
Getting same errors with [doq-proxy](https://github.com/ns1/doq-proxy):

```
./client -server dns.google.com:443 www.paypal.com A
failed to connect to the server: No compatible QUIC version found. We support [QUIC WG draft-19], server offered [0xaaea2aca 0xff00001b 0xff000019 0x54303530 0x51303530 gQUIC 49 gQUIC 48 gQUIC 46 gQUIC 43]
```

**Comment by cbuijs** [comment]
BTW: Not sure if you did add the DoH-over-QUIC yet... So I might testing something weird here :-)

**Comment by cbuijs** [comment]
Also, it seems that the regurlar queries coming from a client, and relayed to a QUIC DNS Server, the ID is set to `0` for the client as well (only should be `0` to the QUIC DNS Server):

```
dig quic.chrisbuijs.com
;; Warning: ID mismatch: expected ID 50451, got 0
```

**Comment by folbricht** [comment]
Sorry, I should have put some examples in here but forgot. So I haven't found a provider that offers plain DoQ yet. What cloudflare-dns.com offers is DoH over QUIC and you can try that.

Use the `issue-33` branch with this config. Notice the `transport` option that's new for DoH server and client.
```toml
[resolvers.cloudflare-doh-quic]
address = "https://cloudflare-dns.com/dns-query{?dns}"
protocol = "doh"
transport = "quic"
```

As for the ID, the DoQ spec requires all queries sent over it to be 0. Though I'm pretty sure I put the original ID back in the response when sent through routedns. See 5.4 in https://www.ietf.org/id/draft-ietf-dprive-dnsoquic-00.txt

**Comment by folbricht** [comment]
Merged in https://github.com/folbricht/routedns/pull/34
