### ISSUE TITLE
Panic in json memory gc

### ISSUE THREAD

**Issue by charlieporth1** [folbricht/routedns#337]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9dbf7a]

goroutine 13 [running]:
github.com/folbricht/routedns.(*memoryBackend).startGC.func1(0xaf8a20?)
        /root/go/pkg/mod/github.com/folbricht/routedns@v0.1.21-0.20230909090456-cdc9b5482760/cache-memory.go:136 +0x1a
github.com/folbricht/routedns.(*lruCache).deleteFunc(0xc004d128e0, 0xc00d167e48)
        /root/go/pkg/mod/github.com/folbricht/routedns@v0.1.21-0.20230909090456-cdc9b5482760/lru-cache.go:174 +0x5b
github.com/folbricht/routedns.(*memoryBackend).startGC(0xc004d0f2c0, 0xc000205f00?)
        /root/go/pkg/mod/github.com/folbricht/routedns@v0.1.21-0.20230909090456-cdc9b5482760/cache-memory.go:135 +0x149
created by github.com/folbricht/routedns.NewMemoryBackend in goroutine 1
        /root/go/pkg/mod/github.com/folbricht/routedns@v0.1.21-0.20230909090456-cdc9b5482760/cache-memory.go:45 +0x1d7
```

I believe this is in reference to this 
[L136](https://github.com/folbricht/routedns/blob/cdc9b54827607caa46db85cffee61a287a096b1a/cache-memory.go#L136C11-L136C11)
@folbricht I could use some guidance

**Comment by folbricht** [comment]
I went through the code and there doesn't seem any place that could store a `nil` answer in the cache, except for one place. And that's where it reads a stored cache from disk. So my current theory is the cache file you have is either damaged or it was an incompatible format. One thing to try would be to just rename the file and start the service without one, that should fix the issue. I can also put a check to ensure bad files don't get loaded.
