### ISSUE TITLE
Too look into... Extended Error Codes

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#345]
Maybe to implement as `static-responder`? (or add option to it)?

See here:
[Extended Error Codes](https://labs.ripe.net/author/yevheniya_nosyk/extended-dns-errors-unlocking-the-full-potential-of-dns-troubleshooting/)

Or maybe in the `blocklist-v2` (or the others) as well, when something is blocked, have the option to set the extended error code to "blocked"?

It is nice when you use `dig` it will show it.

**Comment by folbricht** [comment]
Good idea. Any thoughts on what to call the blocklist_v2 option? As for the `static-responder`, adding an option to it seems to make the most sense.

**Comment by cbuijs** [comment]
`extended-error` with the number of the message. Default would be `false` (or `0`) meaning no extended errors should be added.

**Comment by folbricht** [comment]
Can you try out the `issue-345` branch? It adds the ability to set extended error codes in the `static-responder`. Since the responder could be used as blocklist-resolver I think this should cover most use-cases.

**Comment by cbuijs** [comment]
I tried, but it doesn't compile when combining with `issue-107-names` and `issue-341` branches. Which I need.

I will try with a standard master branch.

**Comment by cbuijs** [comment]
Seems to work, but only returns code `15`, seems to ignore the `code` in the `edns0-ede` statement.

**Comment by folbricht** [comment]
Hmm, I can't repro the issue. Changing the code works as expected, and even using your example whole seems to return the expected values:
```
$ dig -p 1153 @127.0.0.1 .

; <<>> DiG 9.18.19 <<>> -p 1153 @127.0.0.1 .
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62393
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; EDE: 0 (Other): (NOERROR)
;; QUESTION SECTION:
;.				IN	A

;; AUTHORITY SECTION:
.			30	IN	SOA	ns.invalid. hostmaster.invalid. 666 666 666 666 666

;; Query time: 1 msec
;; SERVER: 127.0.0.1#1153(127.0.0.1) (UDP)
;; WHEN: Mon Oct 23 11:51:14 CEST 2023
;; MSG SIZE  rcvd: 104
```

The option code happens to be 15 as well, it's not the error code in the option that it shows. The `..` are null bytes which contain the error code just before the message string. I believe this may be an issue with your version of dig not being able to parse it properly. Perhaps it's too old and doesn't understand the new option yet?

**Comment by cbuijs** [comment]
You right, when I use `kdig` (Knot DIG) it works, the `dig` I used is broken.
```
;; EDNS PSEUDOSECTION:
;; Version: 0; flags: ; UDP size: 4096 B; ext-rcode: NOERROR
;; EDE: 0 (Other): 'NOERROR'
```

**Comment by cbuijs** [comment]
Looks like it works. I'll let it steam for a couple of days and let you know any issues before merge.

**Comment by folbricht** [comment]
Resolved by https://github.com/folbricht/routedns/pull/347
