### ISSUE TITLE
Error with quic client

### ISSUE THREAD

**Issue by nickzhog** [folbricht/routedns#349]
the quic client did not work for me after 1 request, due to the fact that the error ("Application error 0x0 (remote)") did not meet the conditions. Why not recreate the stream at any error?
my pr: https://github.com/nickzhog/routedns/pull/1

**Comment by folbricht** [comment]
I was using the recommended way to check for network errors before, see https://github.com/quic-go/quic-go#accepting-streams, but it shouldn't hurt to simply attempt one restart on any error type. Can try that.

Do you know what kind of error your got?

**Comment by nickzhog** [comment]
> Do you know what kind of error your got?
error type is *qerr.AppicationError
I used 2 listeners, in one of which I received via udp and resolved via quiс on the next, that is, the first listener was a client for the second using the quic protocol. With this use, you will get an error (which was handled incorrectly in the original project) for each repeated request

**Comment by folbricht** [comment]
Should be resolved with https://github.com/folbricht/routedns/pull/350
