### ISSUE TITLE
get routedns

### ISSUE THREAD

**Issue by limbo127** [folbricht/routedns#38]
Hello, 
from readme : 
go get -u github.com/folbricht/routedns/cmd/routedns
=> package crypto/ed25519: unrecognized import path "crypto/ed25519" (import path does not begin with hostname)

Regards, 
Nicolas

**Comment by limbo127** [comment]
Hello, 
just a golang version issue

**Comment by folbricht** [comment]
What version of Go do you use? Just tried the same command with Go 1.14.3 and it worked fine.

Btw, I'm currently in the process of reworking the documentation, so perhaps I should add some version requirments.

**Comment by limbo127** [comment]
Issue with 1.10x  , no issue with 1.14x
thanks
