### ISSUE TITLE
When including branch "issue-366" it breaks build/merge

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#381]
When I merge branch `issue-366` with the current master ([0b33830](https://github.com/folbricht/routedns/commit/0b3383008edbd02e07daa4b5a0c523b724198b69)), it will results in the following merge errors below.

When I remove it from the merge, all is good...

Trying to see what is happening but there is not a lot to hold onto.

```
Trying simple merge with 3c35cc5ab14333244f737bf30d3125e7f5d79b4e
Simple merge did not work, trying automatic merge.
Auto-merging cmd/routedns/main.go
Auto-merging doc/configuration.md
Trying simple merge with 9f95648e4ca69f243c1bbf512bb1e51e2f881160
Simple merge did not work, trying automatic merge.
Auto-merging cmd/routedns/config.go
Auto-merging cmd/routedns/main.go
Auto-merging doc/configuration.md
Trying simple merge with e76d164dcdbbe75e237c1d8385db570683c9208e
Simple merge did not work, trying automatic merge.
Auto-merging cmd/routedns/config.go
Auto-merging cmd/routedns/main.go
Auto-merging doc/configuration.md
Trying simple merge with 32c26d8f7da1bd0942a51fca29fc7e03cf71940b
Simple merge did not work, trying automatic merge.
Auto-merging cmd/routedns/config.go
Auto-merging cmd/routedns/main.go
ERROR: content conflict in cmd/routedns/main.go
Auto-merging static.go
ERROR: content conflict in static.go
fatal: merge program failed
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by cbuijs** [comment]
If I see correctly, the merge to master of `blocklist-ede` 3 days ago, supersedes `issue-366` now, right?

**Comment by folbricht** [comment]
I'm planning to abandon https://github.com/folbricht/routedns/pull/367 (`issue-366`) in favour of https://github.com/folbricht/routedns/pull/378 (`static-template-responder`). Templates are a better way to solve this than regexes. The templated EDE bits should be available on master already, including for the static responder.

**Comment by cbuijs** [comment]
No worries, thanks!
