### ISSUE TITLE
Push version tags

### ISSUE THREAD

**Issue by mikhirev** [folbricht/routedns#390]
Hi!

As I see, new version numbers are generated by github actions. They are tagged but tags are not pushed to the github repo. Instead of this new branches are created for each new version.

I use routedns as a module in my projects. Go tracks module versions by tags and ignore branches, so I'm unable to obtain a new module version unless I specify a commit hash. Please push version tags to the repo. To avoid ref name conflicts, you have to use different names for version branches, e. g. without leading`v` (are that branches really needed?).

**Comment by folbricht** [comment]
Oh, I hadn't realized that wasn't working. I think it may be fixed in https://github.com/folbricht/routedns/pull/391 Can you try now to see if it's working for you?

**Comment by mikhirev** [comment]
Yes, now it's working. Thanks!

**Comment by folbricht** [comment]
Thanks for bringing this up
