### ISSUE TITLE
How to configure client whitelist

### ISSUE THREAD

**Issue by liang-hiwin** [folbricht/routedns#392]
I want to configure that only IPs that comply with CIDR can use dns.

**Comment by liang-hiwin** [comment]
> That seems straightforward, like in https://github.com/folbricht/routedns/blob/master/cmd/routedns/example-config/client-blocklist-drop.toml Just need to set `resolver` to something that blocks, and `blocklist-resolver` to something that forwards the query.

I need a whitelist IP list, such as building a dns server whitelisted IP or a whitelisted country IP before I can use it.

**Comment by folbricht** [comment]
If you need to block/allow responses based on geo location, there's an example in https://github.com/folbricht/routedns/blob/master/cmd/routedns/example-config/response-blocklist-geo.toml#L8 Or if you want to block clients based on location you can look at https://github.com/folbricht/routedns/blob/master/cmd/routedns/example-config/client-blocklist-geo.toml

**Comment by liang-hiwin** [comment]
> If you need to block/allow responses based on geo location, there's an example in https://github.com/folbricht/routedns/blob/master/cmd/routedns/example-config/response-blocklist-geo.toml#L8 Or if you want to block clients based on location you can look at https://github.com/folbricht/routedns/blob/master/cmd/routedns/example-config/client-blocklist-geo.toml

I want to implement a function similar to nginx. For example

allow 1.1.8.0/24;
allow 1.1.8.0/24;
allow 1.116.0.0/15;
.....
deny all;

**Comment by cbuijs** [comment]
It can be done like this:
```
[groups.client-allowlist]
type = "client-blocklist"
resolvers = ["deny-client"]
blocklist-resolver  = "allow-client" # Any match is sent to a resolver that drops the query
blocklist           = [
  '1.1.8.0/24',
  '1.116.0.0/15',
]
```
