### ISSUE TITLE
0-RTT does not work.

### ISSUE THREAD

**Issue by marcelloinfoweb** [folbricht/routedns#407]
I follow the example with 0-RTT enabled
```
[resolvers.cloudflare-doh-quic]
address = "https://cloudflare-dns.com/dns-query"
protocol = "doh"
transport = "quic"
enable-0rtt = true
```

But it doesn't resolve the addresses

**Comment by folbricht** [comment]
When using 0-RTT, the `GET` method is enforced which means the `address` has to be a template. If you update the config like so it'll work:
```toml
address = "https://cloudflare-dns.com/dns-query{?dns}"
```

**Comment by marcelloinfoweb** [comment]
Obrigado!
