### ISSUE TITLE
Possibility to specify both IPv4 and IPV6 addresses for "ecs-address"

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#44]
For the <a href="https://github.com/folbricht/routedns/blob/master/doc/configuration.md#edns0-client-subnet-modifier">`ecs-modifier`</a>, it is only possible to specify one IP-Address with `ecs-address`, regardless when the traffic is IPv4 or IPv6.

It would be nice to specify two addresses, one to use for IPv4 traffic, and one for IPv6 traffic.

E.g. if a query/request goes to an DNS Server with an IPv6 address, use the IPv6 ECS address, and when on IPv4 the IPv4 ECS address.

**Comment by folbricht** [comment]
I can add options for `ecs-address4` and `ecs-address6` and depending on the client's address pick one. Don't think I can update the component itself to choose based on which server is used. To do that, it'd be possible to put an ecs-modifier in front of each resolver though.

What's better, adding `ecs-address4` and `ecs-address6` or removing the dynamic choice completely and use multiple modifiers in the pipeline? The latter may actually be more flexible.

**Comment by cbuijs** [comment]
I already use the multiple modifiers with a router in-front to pick the IPv4 one when the `source` is `0.0.0.0/0` and IPv6 when `::/0` and is very flexible. So it makes sense to keep it like that if the dynamic stuff makes things more inflexible.

**Comment by cbuijs** [comment]
Example:

```
[routers.ecs-router]
routes = [
  { source = "::/0", resolver = "ecs6" },
  { resolver = "ecs4" },
]

[groups.ecs4]
type = "ecs-modifier"
resolvers = ["doh-google4"]
ecs-op = "add"
ecs-address = "123.123.123.123"
ecs-prefix4 = 24

[groups.ecs6]
type = "ecs-modifier"
resolvers = ["doh-google6"]
ecs-op = "add"
ecs-address = "2001:db8:123:123:123:123:123:123"
ecs-prefix6 = 48
```

**Comment by folbricht** [comment]
I suspect that keeping it explicit is the better way here. Actually do have an implementation that takes ecs-address4 and 6 and picks one based on the client's type of address, but after looking at it a bit more, that doesn't seem to be the best way to do it.

**Comment by cbuijs** [comment]
Yeah, makes more sense to keep things as is. Above config works just fine and is pretty straightforward/clean. You can close this if you want/like.
