### ISSUE TITLE
Features for minimal-responses and cname-collapsing

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#46]
To keep packets as small as possible to (stub) clients, and remove any irrelevant information not used by them anyway, there are some features that are interesting to add to optimize resolution (and bandwidth usage):

### Minimal-Responses:
- Remove the `Authoritative` and `Additional` section of the response before sending it to the client for `NOERROR` responses (only).

### CNAME-Collapsing (this is **NOT** CNAME Flattening!):
- Collaps cname-chains into simplified address-answers, removing the chain when `QTYPE` = `A` or `AAAA` and the response to that is a `CNAME` chain.
- Use/Retain the TTL of the address-records

### Example of CNAME-Collapsing:
```
www.paypal.com. 2964 IN CNAME www.glb.paypal.com.
www.glb.paypal.com. 251 IN CNAME www.paypal.com-a.edgekey.net.
www.paypal.com-a.edgekey.net. 7199 IN CNAME e5308.x.akamaiedge.net.
e5308.x.akamaiedge.net. 18 IN A 95.100.196.60
```
becomes:
```
www.paypal.com. 18 IN A 95.100.196.60
```

### Another example but with more address-records:
```
www.amazon.nl. 1460 IN CNAME tp.252df37b2-frontier.amazon.nl.
tp.252df37b2-frontier.amazon.nl. 58 IN CNAME www.amazon.nl.edgekey.net.
www.amazon.nl.edgekey.net. 7199 IN CNAME e15324.e22.akamaiedge.net.
e15324.e22.akamaiedge.net. 18 IN A 23.62.137.202
e15324.e22.akamaiedge.net. 18 IN A 13.225.16.238
e15324.e22.akamaiedge.net. 18 IN A 13.227.216.42
```
becomes:
```
www.amazon.nl. 18 IN A 23.62.137.202
www.amazon.nl. 18 IN A 13.225.16.238
www.amazon.nl. 18 IN A 13.227.216.42
```

**Comment by folbricht** [comment]
Interesting ideas, thanks for the write-up and examples.

**Comment by cbuijs** [comment]
No worries. Also... this makes cache-usage lower, so you can cache more ;-).

**Comment by folbricht** [comment]
Proposed element names:
- `response-minimize` for the piece that strips Extra and NS RRs
- `response-collapse` for compacting chains

**Comment by folbricht** [comment]
Both have been implemented on the `issue-46` branch

```toml
[groups.minimize]
type = "response-minimize"
resolvers = ["google-dot"]
```

```toml
[groups.collapse]
type = "response-collapse"
resolvers = ["google-dot"]
```

**Comment by cbuijs** [comment]
Works as expected, but might need a small (configurable) tweak:

When after a collapse the response is empty, force a NXDOMAIN instead of keeping the NOERROR. Might even think about a resolver exit if needed and do a static NXDOMAIN or anything you want to anticpate.

Example:
`dig www.paypal.com A`
and
`dig www.paypal.com AAAA`

The later one will be empty as there is no AAAA record, this is a common issue with companies/cdn's using CNAMES. With collapsing, now you end up with a "NODATA" (NOERROR with empty answer section). 

This is more of a fix-up for bad usage of DNS by companies and be more elegant about it. It is not strictly neccesary.

**Comment by folbricht** [comment]
Thanks, added that as well. It'll now NXDOMAIN when there's nothing left after collapsting.

**Comment by cbuijs** [comment]
Works as expected.

**Comment by folbricht** [comment]
Thanks, merged in https://github.com/folbricht/routedns/pull/54

**Comment by cbuijs** [comment]
Maybe a bug: When an `nxdomain` is generated when no records are left, and you have a cache in front of the collapser, the `noerror` gets cached, not the generated `nxdomain`.

use `dig help.apple.com aaaa` to test.

**Comment by folbricht** [comment]
Good find. Actual bug in the cache. Fixed on master

**Comment by cbuijs** [comment]
Fixed/Works!
