### ISSUE TITLE
Random and RTT type group

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#48]
Would it be possible to have next to the `Round-Robin`, `Fail-Rotate` and `Fail-Back` type groups, a "random" and "rtt" based one?

Random:
- Would selects resolvers from the resolvers-list at random
- At failure pick next random one (excluding the failed one of course)

RTT:
- Would pick the fastest DNS server (based on previous RTT measured), also called "RTT Banding"
- Update RTT every query done
- Initiate all DNS servers RTT with a random (low) value
- Randomaly or syntechically pick other DNS servers to measure if still fastest
- See <a href="https://books.google.nl/books?id=Xb9O5yNS5GEC&pg=PA30&lpg=PA30&dq=DNS+RTT+Cricket+Liu&source=bl&ots=M9SoePV6fu&sig=ACfU3U0vuQKAelioUV_bFywVtVRkmWOquw&hl=en&sa=X&ved=2ahUKEwiI2fqg5OrpAhWE-aQKHdk6DZQQ6AEwB3oECA8QAQ#v=onepage&q=DNS%20RTT%20Cricket%20Liu&f=false">here</a> RTT example/explaination (Page 30 and 31)

**Comment by folbricht** [comment]
Wrt the random group, what would happen when one of them fails and another one is picked. Should the failed one stay in the list of possible resolvers (to be chosen again by another query), or not get reconsidered for a period of time? Like one failure takes it out of service for N seconds?

**Comment by cbuijs** [comment]
It should be flagged "down" for lets say 60 seconds (maybe configurable?), and not be selected during that time.

**Comment by folbricht** [comment]
First implementation on the `random-resolver` branch. This doesn't yet allow configuration of the time to reset a failed one, it's set to one minute.

**Comment by folbricht** [comment]
Merged in #53
