### ISSUE TITLE
Change behaviour of "filter" when all records are filtered out

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#49]
When using `filter = true` with `response-blocklist-ip`, and all IP's are removed from a response (e.g. empty response), as a result, a NXDOMAIN is returned.

Today, when a `blocklist-responder` is defined, a `NXDOMAIN` is still returned, would it be possible to change this behaviour into this:

- Filter removes IP's from a response
- As result of the filtering, the response is empty:
  - When **NO** `blocklist-responder` is defined, return `NXDOMAIN`
  - When a `blocklist-responder` **IS** defined, follow down that path
- When result of filtering is **NOT** empty, just return the (filtered) response

**Comment by folbricht** [comment]
First draft of the fix on the `issue-49` branch

**Comment by cbuijs** [comment]
Works as expected.

**Comment by folbricht** [comment]
oops, forgot to remove that part, done now.

**Comment by cbuijs** [comment]
Works as expected now. Smooth sailing!
