### ISSUE TITLE
Allow an "include" statement to refer to another toml file for config to be included

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#5]
Hi,

Subject says it all basically.

Basically if you want to generate/automate toml files it becomes handy in auto-config environment. Pointing it to a "conf.d" directory and read all toml files from there would be paradise on this :-).

Cheers,
-Chris.

**Comment by folbricht** [comment]
How about allowing multiple files on the command-line? Could look like:
```
routedns /etc/routedns/conf.d/*.conf /some/other/file.conf
```

**Comment by cbuijs** [comment]
@folbricht 

Elegant alternative!

**Comment by folbricht** [comment]
Done in https://github.com/folbricht/routedns/pull/6, give it a try. All it does is to concatenate the different files and then load it whole. See https://github.com/folbricht/routedns/tree/master/cmd/routedns/example-config/split-config for an exmple

**Comment by cbuijs** [comment]
Works great!
