### ISSUE TITLE
For some functions TTL defaults to (hardcoded) 3600

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#52]
Seems that `blocklist` and `static` define a default TTL for the answer-section of `3600` without able to modify it. For `static` you can in the `ns` and `additional` section, but **NOT** `answer` (it ignores the TTL when specfied same way as in `ns` and `additional`).

E.g., the following in a `static` does work as an answer (no errors or breakage), but reverts to TTL of 3600:
`answer = ["2400 IN A 0.0.0.0"]`

`Blocklist` seems to be hardcoded anyway:
https://github.com/folbricht/routedns/blob/36018e4e43b3c83df4efffebb0b983e9a612514c/blocklist.go#L111
https://github.com/folbricht/routedns/blob/36018e4e43b3c83df4efffebb0b983e9a612514c/blocklist.go#L125

Of course you could can put a `ttl-modifier `in front, but that seems to be a bit clumsy and double-up.

**Comment by folbricht** [comment]
The two lines from blocklist.go are only for spoofed records from hosts-format blocklists. It shouldn't affect anything else. Static shouldn't set a fixed TTL either, that would be a bug

**Comment by cbuijs** [comment]
Gotcha. Just figuring out why on statics the TTL for the answer section is 3600 and was wondering if the blocklist had something to do with it. Could it be a library default? 3600 is VERY common in DNS land.

**Comment by cbuijs** [comment]
Here you go:
https://github.com/miekg/dns/blob/203ad2480beb9330454efc215d21f16c607e8174/scan.go#L99

**Comment by folbricht** [comment]
The issue is simply the parser, if you start the zone-file line with TTL it thinks that's the name. It'll work if you put anything in front of the TTL. The name is replaced anyway at runtime to match the query

```toml
answer = [". 2400 IN A 0.0.0.0"]
```

**Comment by cbuijs** [comment]
Confirmed! This is just documentation then I guess.

**Comment by folbricht** [comment]
Updated the documentation to point out how to set the TTL of static answerts.

As for setting TTL of host-file blocklists, I think 3600 is reasonable for now. It can be made configurable if there's a real need for it later.
