### ISSUE TITLE
When using CIDR format for IP blocklists, IP-Address without bitmask not allowed

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#58]
When using blocklists in the cidr format, ip-addresses without a bitmask are not allowed.

It would be goog to assume single-ip for these and assume `/32` for IPv4 and `/128` for IPv6.

Examle:
`37.59.36.210` -> `37.59.36.210/32`
`2001:db8::1:2:3:4` -> `2001:db8::1:2:3:4/128`

Now an error is generated:
`Error: blocklist-ip: invalid CIDR address: 37.59.36.210`

**Comment by folbricht** [comment]
Implemented on the `issue-58` branch

**Comment by folbricht** [comment]
Addressed in https://github.com/folbricht/routedns/pull/62
