### ISSUE TITLE
Subnet-based caching

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#61]
To make sure, especially when using ECS, that a cache responds with the best answer based on ECS or Client-IP proximity.

The premise is that normally load-balancers and CDN's provide different (DNS) answers based on either the client-ip or ECS information of a DNS request. If the first requests get cached, it would give the same answer back to any DNS clients doine subsequent requests, even when the answer is not for their subnet/geo-location.

This is normal called "SubnetCache", basically the hash used as key in the cache "database" is extended using the client-ip. It doesn't have to be the /32 (IPv4) or /128 (IPv6), but based on the assumption that most addresses in a particular subnet-range need the same answers.

Calculation of this subnet is done to calculate the prefix based on the client-ip and is based on assumption. Popular sizes are /24 for IPv4 and /56 for IPv6.

See <a href="https://developers.google.com/speed/public-dns/docs/ecs">here</a> for more insights. The <a href="https://nlnetlabs.nl/documentation/unbound/unbound.conf/">UNBOUND</a> subnetcache is the practical example.

**Comment by folbricht** [comment]
If I understand it correctly, it'd be enough to include not the client IP in the cache key, but the ECS option in the query.

**Comment by cbuijs** [comment]
Not really, the client IP should be used to synthesize the subnet it is from, and that subnet should be used as key. Synthesizing the subnet should be applying a bit-mask to the client-ip and use the result as key. Defaults/suggestion in the original ticket.

When ECS option is there, that could be (optionally) used instead. But an override like the ecs-privacy config items should be possible.

**Comment by folbricht** [comment]
A first implementation is available on the `issue-61` branch. It includes any ECS subnet address in the cache-key to allow different responses per location.

**Comment by folbricht** [comment]
Merged in #73
