### ISSUE TITLE
Logging: Add TYPE to log messages

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#68]
For debugging and visibility/monitoring it might be handy to add `type` to the logging.

Today, when blocking or filtering on `type`, and a rule is hit, it is not clear if it was hit by `name`, `type` etc... If a combo (`name` + `type` for example), is used, the `rule` hit should explain this more clear as well.

For example this:
`level=debug msg="received query" addr=":53" client=176.32.34.129 id=do53-udp protocol=udp qname=.`

becomes this:
`level=debug msg="received query" addr=":53" client=176.32.34.129 id=do53-udp protocol=udp qname=. type=SOA`

This should carry through all log messages as is already done for `client`, `qname`, etc...

**Comment by folbricht** [comment]
That's implemented on the `issue-68` branch. It should show `qtype=` in addition to the existing `qname=`

**Comment by folbricht** [comment]
merged in https://github.com/folbricht/routedns/pull/69
