### ISSUE TITLE
IPv6 address need check. Should throw exception, if format illegal.

### ISSUE THREAD

**Issue by iamsurfing** [folbricht/routedns#76]
If IP format is illegal should throw exception.

Illegal example like this:
  [resolvers.google]
  address="2001:4860:4860::8888:53"
  protocol="tcp"

Correct format like this:
address="[2001:4860:4860::8888]:53"

I do not know whether IPv4 address has the same problem.

**Comment by folbricht** [comment]
The failure actually does happen and is reported in the logs, but only once the resolver is trying to connect at runtime which could be missed. I added input-validation that checks resolver addresses on startup on the `issue-76` branch. It validates not just IPs but also hostnames. Feel free to give it a try, I'll be merging it the coming days.

**Comment by iamsurfing** [comment]
That is good.
