### ISSUE TITLE
http2: timeout awaiting response headers

### ISSUE THREAD

**Issue by wiserain** [folbricht/routedns#86]
First of all, thanks for all about routedns.

I use cloudflare DoH GET mostly to resolve query requests, but some of domains fail with error log in this issue title: "http2: timeout awaiting response headers"

According to the log message, I observed 20~50 cases a day in average. And frequent domains experiencing the problem are ```plex.direct```, ```be.archive.ubuntu.com```, ```probe.performance.dropbox.com```, ```gmpg.org```.

Today I tried with other dns proxy like https://github.com/AdguardTeam/dnsproxy, and it seems not having failure cases like the one with timeout so far.

I would like to know if there's anyone have problems like this, and if so, what the the problem cause and solutions.

**Comment by folbricht** [comment]
I'll take a look at it this weekend. The timeout is a bit tight, just 1 second (https://github.com/folbricht/routedns/blob/master/dohclient.go#L190). I wonder if it's just really that slow sometimes. Going to try putting up the timeout a bit and see how long it takes to resolve those.

**Comment by wiserain** [comment]
Using [AdguardTeam/dnsproxy](https://github.com/AdguardTeam/dnsproxy), I found the following in debug log

```
2020/08/21 04:08:39 1#26167 [debug] github.com/AdguardTeam/dnsproxy/proxy.exchangeWithUpstream(): upstream https://1.1.1.1:443/dns-query successfully finished exchange of ;be.archive.ubuntu.com.	IN	 AAAA. Elapsed 1968 ms.
```

showing that for domains I referred sometime take almost 2 seconds to resolve query request. So I believe increasing timeout value more than 1 second possibly sort this problem out. Is it configurable in config.toml? 

Thanks.

**Comment by wiserain** [comment]
Still some of them and even few new ones come up with timeout message. I guess I have to try using a TTL modifier as suggested. Closing this, but will update if any progress. Thanks!
