### ISSUE TITLE
How to configure dot/doh in vps?

### ISSUE THREAD

**Issue by thb007** [folbricht/routedns#92]
How to configure dot/doh in vps? I want to configure them on vps, do I need 2 toml configuration files?

**Comment by folbricht** [comment]
Depends on what you're trying to do. You only need one config file for a single routedns process. And a single process can have multiple server/client implementation, so in most cases a single one should be sufficient.

**Comment by thb007** [comment]
> Depends on what you're trying to do. You only need one config file for a single routedns process. And a single process can have multiple server/client implementation, so in most cases a single one should be sufficient.

This is the file and configuration I compiled according to your source code. Can you help me see why it can't start?

[routedns.zip](https://github.com/folbricht/routedns/files/5320948/routedns.zip)

**Comment by thb007** [comment]
```
root@i:/opt/routedns# ./routedns
Error: requires at least 1 arg(s), only received 0


```

**Comment by folbricht** [comment]
Not looked at your config yet, but the command above is missing a parameter. The config file is the first parameter. You can see that with `routedns -h` as well. So likely all you need is to run it like so `./routedns config.toml`

**Comment by thb007** [comment]
> Not looked at your config yet, but the command above is missing a parameter. The config file is the first parameter. You can see that with `routedns -h` as well. So likely all you need is to run it like so `./routedns config.toml`

Hello, how to solve this!

```
2020/10/03 15:43:20 http: TLS handshake error from ip:39690: tls: client didn't provide a certificate
2020/10/03 15:43:24 http: TLS handshake error from ip:44124: tls: client didn't provide a certificate
2020/10/03 15:43:28 http: TLS handshake error from ip:39924: tls: client didn't provide a certificate
2020/10/03 15:43:28 http: TLS handshake error from ip:39932: tls: client didn't provide a certificate
2020/10/03 15:43:28 http: TLS handshake error from ip:39944: tls: client didn't provide a certificate
2020/10/03 15:43:29 http: TLS handshake error from ip:39948: tls: client didn't provide a certificate
2020/10/03 15:43:29 http: TLS handshake error from ip:40102: tls: client didn't provide a certificate

```

**Comment by folbricht** [comment]
The issue is that your DoH listener is configured for mutual-TLS, which means anything connecting to it needs to provide a (trusted) client certificate. In this case something connected to it without providing a cert. Not sure if you intended to use mutual TLS, but I suspect you can just remove the `mutual-tls` and the `ca` option from the listener below.
```
[listeners.local-doh]
address = ":4433"
protocol = "doh"
resolver = "rrl"
server-crt = "/opt/AdGuardHome/domain.crt"
server-key = "/opt/AdGuardHome/domain.key"
ca = "/etc/ssl/certs/ca-certificates.crt"
mutual-tls = true
```

**Comment by thb007** [comment]
> The issue is that your DoH listener is configured for mutual-TLS, which means anything connecting to it needs to provide a (trusted) client certificate. In this case something connected to it without providing a cert. Not sure if you intended to use mutual TLS, but I suspect you can just remove the `mutual-tls` and the `ca` option from the listener below.
> 
> ```
> [listeners.local-doh]
> address = ":4433"
> protocol = "doh"
> resolver = "rrl"
> server-crt = "/opt/AdGuardHome/domain.crt"
> server-key = "/opt/AdGuardHome/domain.key"
> ca = "/etc/ssl/certs/ca-certificates.crt"
> mutual-tls = true
> ```

I tested it
