### ISSUE TITLE
HOPE:If resolver1 return SERVFAIL, ROUTEDNS should treat as request failed and switch to resolver2.

### ISSUE THREAD

**Issue by iamsurfing** [folbricht/routedns#99]
[groups.group1]
  resolvers=["resolver1","resolver2"]
  type="fail-rotate"

NOW: If resolver1 return SERVFAIL, group1 will return SERVFAIL to downstream.

HOPE: If resolver1 return SERVFAIL, ROUTEDNS should treat as request failed and switch to resolver2. Then send the same requestion to resolver2.If both request failed, return SERVFAIL to downstream.

REASON: If some public DNS wait timeout, it will return SERVFAIL until get answer. Sometimes It is just network problem between NS server and public DNS server.

**Comment by folbricht** [comment]
Yes, I agree. Currently only a complete failure to get a response counts as an error that causes a failover. Should be an easy fix, I'll look into it.

**Comment by iamsurfing** [comment]
Otherwise, you can add a switch to control this following.

**Cache SERVFAIL responses (#91) #98**

[https://github.com/folbricht/routedns/pull/98](url)

@mikhirev What do you think about it?

**Comment by iamsurfing** [comment]
However, I still think the top post is the best solution.

**Comment by folbricht** [comment]
I did go with the first suggestion for now, it makes the most sense I think. Feel free to try it out on the `issue-99` branch.

**Comment by iamsurfing** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x15bc0bd]

goroutine 40 [running]:
github.com/folbricht/routedns.(*FailRotate).Resolve(0xc0000725a0, 0xc000140360, 0xc0003bc10c, 0x10, 0x10, 0xc000159750, 0x12a0c6c, 0xc00003b860)
        /go/pkg/mod/github.com/folbricht/routedns@v0.0.0-20201107185713-f6f7f2700c3f/failrotate.go:44 +0x63d
github.com/folbricht/routedns.(*ResponseBlocklistIP).Resolve(0xc0001a6bd0, 0xc000140360, 0xc0003bc10c, 0x10, 0x10, 0xc0000a38c8, 0xc0000a38c8, 0xc0001a14ba)
        /go/pkg/mod/github.com/folbricht/routedns@v0.0.0-20201107185713-f6f7f2700c3f/response-blocklist-ip.go:60 +0x67
github.com/folbricht/routedns.(*ResponseBlocklistIP).Resolve(0xc0001a6c40, 0xc000140360, 0xc0003bc10c, 0x10, 0x10, 0x1, 0xc000111880, 0xc000028c00)
        /go/pkg/mod/github.com/folbricht/routedns@v0.0.0-20201107185713-f6f7f2700c3f/response-blocklist-ip.go:60 +0x67
github.com/folbricht/routedns.(*Router).Resolve(0xc000394870, 0xc000140360, 0xc0003bc10c, 0x10, 0x10, 0x10, 0x1, 0x2030000)
        /go/pkg/mod/github.com/folbricht/routedns@v0.0.0-20201107185713-f6f7f2700c3f/router.go:61 +0x370
github.com/folbricht/routedns.listenHandler.func1(0x1885220, 0xc0000fe8a0, 0xc000140360)
        /go/pkg/mod/github.com/folbricht/routedns@v0.0.0-20201107185713-f6f7f2700c3f/dnslistener.go:71 +0x6d3
github.com/miekg/dns.HandlerFunc.ServeDNS(0xc0001a7ce0, 0x1885220, 0xc0000fe8a0, 0xc000140360)
        /go/pkg/mod/github.com/miekg/dns@v1.1.32/server.go:37 +0x4b
github.com/miekg/dns.(*Server).serveDNS(0xc0001fd0e0, 0xc0000c0640, 0x3c, 0x3c, 0xc0000fe8a0)
        /go/pkg/mod/github.com/miekg/dns@v1.1.32/server.go:617 +0x2f7
github.com/miekg/dns.(*Server).serveTCPConn(0xc0001fd0e0, 0xc00038be40, 0x1885400, 0xc0000065d0)
        /go/pkg/mod/github.com/miekg/dns@v1.1.32/server.go:525 +0x219
created by github.com/miekg/dns.(*Server).serveTCP
        /go/pkg/mod/github.com/miekg/dns@v1.1.32/server.go:442 +0x365

You can not merge this branch, because it is not stable. It will crash after get SERVFAIL response. (My golang version is 1.15.3.)

**Comment by cbuijs** [comment]
Maybe implement the "hop to next resolver" when getting servfail, and add servfail at the end as a static?

```
[groups.the-internet]
type = "fail-back"
resolvers = ["doh-google1", "doh-google", "servfail"]

[groups.servfail]
type  = "static-responder"
rcode = 2
```

**Comment by folbricht** [comment]
Oops, I see the issue. Do you happen to have a drop resolver after the fail-rotate? Simple fix...

**Comment by folbricht** [comment]
Pushed a fix for that case, try again now. It'll properly handle drops

**Comment by iamsurfing** [comment]
I have tested it. It seems ok. Thanks.

**Comment by iamsurfing** [comment]
@folbricht 

I am sorry I found this problem after you closed this issue.

NOW:if resolver1&2 return SERVFAIL, it will not respound this request. DIG tool will print timeout error.(probably infinite switch)

HOPE:if resolver1&2 return SERVFAIL, it will return SERVFAIL **immediately**.

**Comment by folbricht** [comment]
Missed that, it's fixed in https://github.com/folbricht/routedns/pull/103 now if you want to give it another try. It'll return the failure of the last resolver in the group that is tried.
